import { escapeHtml } from './dom.js';

/**
 * Help ▸ Licenses — this app's own license plus every third-party notice.
 *
 * Not decorative: the app bundles pm2 under AGPL-3.0, which is why the app
 * itself is AGPL-3.0-or-later, and those notices have to travel with the
 * binary.
 *
 * The data comes from src/assets/licenses.json, generated by
 * `npm run licenses` and fetched over IPC — the renderer's CSP sets
 * connect-src 'none', so it cannot fetch() the file itself, and ~190KB of
 * license text does not belong in the module graph either.
 *
 * Each package renders as a <details> so the list stays scannable and the full
 * texts are one click away rather than a wall.
 */

let openDialog = null;
let opening = false;

function packageRow(entry) {
  const heading = `${escapeHtml(entry.name)} ${escapeHtml(entry.version ?? '')}`.trim();
  const body = entry.text
    ? `<pre class="license-text">${escapeHtml(entry.text)}</pre>`
    : `<p class="license-missing">This package ships no license file. Declared license:
       <strong>${escapeHtml(entry.license)}</strong>.${
         entry.homepage
           ? ` See <a href="#" data-external="${escapeHtml(entry.homepage)}">${escapeHtml(entry.homepage)}</a>.`
           : ''
       }</p>`;

  return `
    <details class="license-entry">
      <summary><span class="license-name">${heading}</span>
        <span class="license-id">${escapeHtml(entry.license)}</span></summary>
      ${body}
    </details>
  `;
}

function runtimeSection(runtime) {
  if (!runtime) return '';
  return `
    <h3>Installed at setup, not bundled</h3>
    <p class="license-note">${escapeHtml(runtime.note)}</p>
    <ul class="license-runtime">
      ${(runtime.packages ?? [])
        .map(
          (p) => `<li><strong>${escapeHtml(p.name)}</strong>
            <span class="license-id">${escapeHtml(p.license)}</span>
            ${p.note ? `<br /><span class="license-note">${escapeHtml(p.note)}</span>` : ''}</li>`,
        )
        .join('')}
    </ul>
  `;
}

/**
 * @param {{app: {getLicenses: () => Promise<{ok: boolean, data?: object, error?: {message: string}}>, openExternal: (arg: {url: string}) => Promise<any>}}} nimProxy
 */
export async function showLicensesDialog(nimProxy) {
  if (openDialog) {
    openDialog.focus();
    return;
  }
  // Same synchronous latch as about-dialog.js: openDialog is only assigned
  // after the awaited load, so without this two quick clicks stack two dialogs.
  if (opening) return;
  opening = true;

  let result;
  try {
    result = await nimProxy.app.getLicenses();
  } finally {
    opening = false;
  }

  const dialog = document.createElement('dialog');
  dialog.className = 'licenses-dialog';

  const body = result?.ok
    ? `
      <h3>${escapeHtml(result.data.app.name)} ${escapeHtml(result.data.app.version)}</h3>
      <p class="license-note">Licensed under <strong>${escapeHtml(result.data.app.license)}</strong>.</p>
      <details class="license-entry">
        <summary><span class="license-name">Full license text</span>
          <span class="license-id">${escapeHtml(result.data.app.license)}</span></summary>
        <pre class="license-text">${escapeHtml(result.data.app.text)}</pre>
      </details>

      <h3>Bundled in this application (${result.data.bundled.length})</h3>
      ${result.data.bundled.map(packageRow).join('')}

      ${runtimeSection(result.data.runtime)}
    `
    : `<p class="license-missing">${escapeHtml(result?.error?.message ?? 'Licenses are unavailable.')}</p>`;

  dialog.innerHTML = `
    <form method="dialog">
      <h2>Licenses</h2>
      <div class="licenses-scroll">${body}</div>
      <div class="confirm-dialog-actions">
        <button value="close" class="primary" data-role="close">Close</button>
      </div>
    </form>
  `;
  document.body.append(dialog);
  openDialog = dialog;

  // Navigation is locked to file:// (windows.js), so homepage links have to go
  // out through the allowlisted IPC channel.
  dialog.addEventListener('click', (event) => {
    const link = event.target.closest('[data-external]');
    if (!link) return;
    event.preventDefault();
    nimProxy.app.openExternal({ url: link.dataset.external });
  });

  dialog.addEventListener('close', () => {
    dialog.remove();
    openDialog = null;
  }, { once: true });

  dialog.showModal();
  dialog.querySelector('[data-role="close"]')?.focus();
}
