'use strict';

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const { createEngineContext } = require('../../src/main/engine-context');
const { generateAll } = require('../../src/engine/configGen');
const paths = require('../../src/engine/paths');

// Mirrors test/main/engine-context-apikey.test.js's withFakeHome — the only
// sanctioned way (per CLAUDE.md) to point createEngineContext() at a
// throwaway directory instead of this machine's real ~/.config/claude-conduit.
function withFakeHome(fn) {
  const homeDir = fs.mkdtempSync(path.join(os.tmpdir(), 'nim-engine-context-regen-test-'));
  const argvHadDev = process.argv.includes('--dev');
  const originalTestHome = process.env.NIM_PROXY_TEST_HOME;
  if (!argvHadDev) process.argv.push('--dev');
  process.env.NIM_PROXY_TEST_HOME = homeDir;
  return Promise.resolve()
    .then(() => fn(homeDir))
    .finally(() => {
      if (!argvHadDev) {
        const idx = process.argv.indexOf('--dev');
        if (idx !== -1) process.argv.splice(idx, 1);
      }
      if (originalTestHome === undefined) delete process.env.NIM_PROXY_TEST_HOME;
      else process.env.NIM_PROXY_TEST_HOME = originalTestHome;
      fs.rmSync(homeDir, { recursive: true, force: true });
    });
}

function fakeSafeStorage() {
  return {
    isEncryptionAvailable: () => true,
    encryptString: (s) => Buffer.from(`enc:${s}`, 'utf8'),
    decryptString: (b) => b.toString('utf8').slice(4),
  };
}

// NCOW-30: createEngineContext hardcodes require('pm2') for its REAL
// pm2Control (see engine-context.js) — every existing test in this repo
// (engine-context-apikey.test.js, shutdown.test.js's own fakePm2 pattern)
// carefully avoids exercising any pm2-touching code path for exactly that
// reason: connecting to/spawning a real system pm2 daemon during `npm test`
// is not something any test here does. engine-context.js's optional
// deps.pm2Control override (added for this task) lets this test observe the
// NCOW-30 stale-config-regeneration wiring end to end without ever touching
// a real pm2 daemon.
function fakePm2Control({ status = 'not-installed' } = {}) {
  const calls = { getStatus: 0, startOrRestart: [] };
  return {
    calls,
    pm2Control: {
      APP_NAME: 'litellm-nim',
      getStatus: async () => {
        calls.getStatus += 1;
        return { status };
      },
      startOrRestart: async (opts) => {
        calls.startOrRestart.push(opts);
        return { ok: true };
      },
    },
  };
}

/**
 * NCOW-31: regenerateStaleConfig() now logs its restart outcome, and
 * engine-context.js passes `deps.logger ?? console` through to it. Tests inject
 * a recorder so the distinct success/failure lines can be asserted directly
 * instead of scraped out of process stdout.
 */
function recordingLogger() {
  const warned = [];
  const infoed = [];
  return { warn: (m) => warned.push(m), info: (m) => infoed.push(m), warned, infoed };
}

/**
 * Lays down exactly what a real pre-NCOW-30 install has on disk: a config
 * directory generated by generateAll() (version-agnostic — this is honestly
 * what an old build's setup wizard produced) plus a manifest.json with no
 * generated_by_version field at all, since that field never existed before
 * this task.
 */
function seedStaleInstall(homeDir) {
  const configDir = paths.resolveConfigDir({ homedir: homeDir });
  const files = paths.getFilePaths(configDir);

  generateAll({
    files,
    primaryModelId: 'meta/llama-3.1-8b-instruct',
    smallModelId: 'meta/llama-3.1-8b-instruct',
    nimBaseUrl: undefined,
    port: 4000,
    litellmAbsPath: '/usr/local/bin/litellm',
    nvidiaApiKey: 'nvapi-old-install',
  });

  const manifest = {
    version: 1,
    port: 4000,
    primary_model: 'meta/llama-3.1-8b-instruct',
    small_model: 'meta/llama-3.1-8b-instruct',
    nim_base_url: null,
    litellm_path: '/usr/local/bin/litellm',
    pm2_app: 'litellm-nim',
    cli_configured: false,
    secret_store_backend: 'electron-safeStorage',
  };
  fs.writeFileSync(files.manifestJson, JSON.stringify(manifest, null, 2) + '\n', 'utf8');

  return files;
}

test('createEngineContext: an upgraded install (stale generated config, older/no version marker) regenerates on launch without re-running setup', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedStaleInstall(homeDir);
    const { pm2Control, calls } = fakePm2Control({ status: 'not-installed' });

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger: recordingLogger(),
    });

    const result = await context.configRegeneration;
    assert.deepEqual(result, { regenerated: true, restarted: false });

    const manifestAfter = JSON.parse(fs.readFileSync(files.manifestJson, 'utf8'));
    assert.equal(manifestAfter.generated_by_version, '0.2.0');

    const cjs = fs.readFileSync(files.ecosystemConfig, 'utf8');
    assert.match(cjs, /interpreter:\s*process\.execPath,/);
    assert.match(cjs, /PYTHONIOENCODING/);

    // Not running at launch (the ordinary case — see NCOW-4) — no restart.
    assert.equal(calls.getStatus, 1);
    assert.equal(calls.startOrRestart.length, 0);
  });
});

test('createEngineContext: AC#2 — regenerating while the proxy is already running restarts it the same way proxy.start()/restart() do', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedStaleInstall(homeDir);
    const { pm2Control, calls } = fakePm2Control({ status: 'running' });

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger: recordingLogger(),
    });

    const result = await context.configRegeneration;
    assert.deepEqual(result, { regenerated: true, restarted: true });

    assert.equal(calls.startOrRestart.length, 1);
    assert.deepEqual(calls.startOrRestart[0], {
      ecosystemConfigPath: files.ecosystemConfig,
      port: 4000,
      outLog: files.outLog,
      errLog: files.errLog,
    });
  });
});

test('createEngineContext: a fresh install (no manifest yet) never touches pm2, regardless of appVersion', async () => {
  await withFakeHome(async (homeDir) => {
    const { pm2Control, calls } = fakePm2Control();

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger: recordingLogger(),
    });

    const result = await context.configRegeneration;
    assert.deepEqual(result, { regenerated: false, reason: 'up-to-date' });
    assert.equal(calls.getStatus, 0);
    assert.equal(calls.startOrRestart.length, 0);
  });
});

test('createEngineContext: an already up-to-date install is a no-op on the next launch', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedStaleInstall(homeDir);
    const manifest = JSON.parse(fs.readFileSync(files.manifestJson, 'utf8'));
    manifest.generated_by_version = '0.2.0';
    fs.writeFileSync(files.manifestJson, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
    const before = fs.readFileSync(files.ecosystemConfig, 'utf8');

    const { pm2Control, calls } = fakePm2Control({ status: 'running' });
    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger: recordingLogger(),
    });

    const result = await context.configRegeneration;
    assert.deepEqual(result, { regenerated: false, reason: 'up-to-date' });
    assert.equal(calls.getStatus, 0, 'must never check proxy status when nothing needs regenerating');
    assert.equal(fs.readFileSync(files.ecosystemConfig, 'utf8'), before);
  });
});

test('createEngineContext: omitting appVersion disables the check entirely (existing callers/tests that never pass it are unaffected)', async () => {
  await withFakeHome(async (homeDir) => {
    seedStaleInstall(homeDir);
    const { pm2Control, calls } = fakePm2Control({ status: 'running' });

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      pm2Control,
      logger: recordingLogger(),
    });

    const result = await context.configRegeneration;
    assert.deepEqual(result, { regenerated: false, reason: 'up-to-date' });
    assert.equal(calls.getStatus, 0);
  });
});

// Fix-pass regression test (review of this task's first pass): a
// truncated/corrupt manifest.json must never crash createEngineContext()
// itself. readManifest() does a bare JSON.parse, and this file gets
// rewritten by writeManifest() on every regeneration (non-atomic
// writeFileSync) — so a crash/power-loss/disk-full mid-write leaves exactly
// this shape on disk, and every future upgrade is a fresh opportunity to hit
// it. Before the fix, this threw synchronously out of createEngineContext()
// itself (not inside the promise chain), which app.whenReady().then(...) in
// index.js has no .catch() for — an unhandled rejection with zero renderers.
test('createEngineContext: a corrupt/truncated manifest.json does not throw out of createEngineContext(), and is treated as absent', async () => {
  await withFakeHome(async (homeDir) => {
    const configDir = paths.resolveConfigDir({ homedir: homeDir });
    const files = paths.getFilePaths(configDir);
    fs.mkdirSync(configDir, { recursive: true });
    fs.writeFileSync(files.manifestJson, '{ "version": 1, "port": 40', 'utf8');

    const { pm2Control, calls } = fakePm2Control({ status: 'running' });

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger: recordingLogger(),
    });

    const result = await context.configRegeneration;
    // needsRegeneration() already treats an absent manifest as nothing to
    // regenerate — a corrupt manifest is deliberately folded into that same
    // safe path rather than treated as a distinct error.
    assert.deepEqual(result, { regenerated: false, reason: 'up-to-date' });
    assert.equal(calls.getStatus, 0);
    assert.equal(calls.startOrRestart.length, 0);
  });
});

test('createEngineContext: a stale manifest with no litellm_path skips regeneration instead of generating with an undefined path', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedStaleInstall(homeDir);
    const manifest = JSON.parse(fs.readFileSync(files.manifestJson, 'utf8'));
    delete manifest.litellm_path;
    fs.writeFileSync(files.manifestJson, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
    const cjsBefore = fs.readFileSync(files.ecosystemConfig, 'utf8');

    const { pm2Control, calls } = fakePm2Control({ status: 'running' });
    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger: recordingLogger(),
    });

    const result = await context.configRegeneration;
    assert.deepEqual(result, { regenerated: false, reason: 'no-litellm-path' });
    assert.equal(calls.getStatus, 0, 'must bail before ever checking proxy status');
    assert.equal(calls.startOrRestart.length, 0);
    assert.equal(fs.readFileSync(files.ecosystemConfig, 'utf8'), cjsBefore, 'must not overwrite the generated config with garbage');
  });
});

test('createEngineContext: a THROWN restart during regeneration resolves (never rejects) and reports the restart-error shape', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedStaleInstall(homeDir);
    const calls = { getStatus: 0 };
    const pm2Control = {
      APP_NAME: 'litellm-nim',
      getStatus: async () => {
        calls.getStatus += 1;
        return { status: 'running' };
      },
      startOrRestart: async () => {
        throw new Error('pm2 restart failed: HEALTH_CHECK_TIMEOUT');
      },
    };
    const logger = recordingLogger();

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger,
    });

    // Must resolve, never reject — this is what keeps a failed restart from
    // ever becoming an unhandled rejection at startup.
    const result = await context.configRegeneration;
    assert.equal(result.regenerated, false);
    // NCOW-31: 'restart-error' rather than the old catch-all 'error' — the
    // failure is now recognised and handled where it happens, not swallowed by
    // engine-context.js's outer .catch(). That outer catch remains, for any
    // *other* throw (e.g. generateAll() failing on a read-only disk).
    assert.equal(result.reason, 'restart-error');
    assert.match(result.error.message, /HEALTH_CHECK_TIMEOUT/);
    assert.equal(calls.getStatus, 1);

    // AC#2: unstamped on disk, and logged distinctly from success.
    const manifestAfter = JSON.parse(fs.readFileSync(files.manifestJson, 'utf8'));
    assert.equal(manifestAfter.generated_by_version, undefined);
    assert.deepEqual(logger.infoed, []);
    assert.equal(logger.warned.length, 1);
    assert.match(logger.warned[0], /THREW/);
  });
});

test('createEngineContext: AC#2 — a TIMED-OUT restart ({ok:false, HEALTH_CHECK_TIMEOUT}) leaves generated_by_version unstamped on disk', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedStaleInstall(homeDir);
    const pm2Control = {
      APP_NAME: 'litellm-nim',
      getStatus: async () => ({ status: 'running' }),
      // pm2Control.startOrRestart()'s real timeout return: no throw at all.
      // Before NCOW-31 this shape was never even inspected, so the manifest was
      // stamped and this launch's failure became permanent.
      startOrRestart: async () => ({
        ok: false,
        error: { code: 'HEALTH_CHECK_TIMEOUT', message: 'litellm did not become healthy in time.' },
        outTail: [],
        errTail: [],
      }),
    };
    const logger = recordingLogger();

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger,
    });

    const result = await context.configRegeneration;
    assert.equal(result.regenerated, false);
    assert.equal(result.reason, 'restart-failed');
    assert.equal(result.error.code, 'HEALTH_CHECK_TIMEOUT');

    const manifestAfter = JSON.parse(fs.readFileSync(files.manifestJson, 'utf8'));
    assert.equal(manifestAfter.generated_by_version, undefined, 'a timed-out restart must not stamp the manifest');
    assert.deepEqual(logger.infoed, []);
    assert.equal(logger.warned.length, 1);
    assert.match(logger.warned[0], /FAILED/);
    assert.match(logger.warned[0], /HEALTH_CHECK_TIMEOUT/);
  });
});

test('createEngineContext: AC#3b — the NEXT launch retries a failed regeneration against the real on-disk manifest', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedStaleInstall(homeDir);

    const deps = () => ({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      logger: recordingLogger(),
    });

    // Launch 1 — restart times out.
    const firstRestarts = [];
    const firstResult = await createEngineContext({
      ...deps(),
      pm2Control: {
        APP_NAME: 'litellm-nim',
        getStatus: async () => ({ status: 'running' }),
        startOrRestart: async (opts) => {
          firstRestarts.push(opts);
          return { ok: false, error: { code: 'HEALTH_CHECK_TIMEOUT', message: 'nope' } };
        },
      },
    }).configRegeneration;
    assert.equal(firstResult.reason, 'restart-failed');
    assert.equal(firstRestarts.length, 1);

    // Launch 2 — brand-new context, reading the SAME manifest.json back off
    // disk. This is the whole point: it must still look stale.
    const secondRestarts = [];
    const secondResult = await createEngineContext({
      ...deps(),
      pm2Control: {
        APP_NAME: 'litellm-nim',
        getStatus: async () => ({ status: 'running' }),
        startOrRestart: async (opts) => {
          secondRestarts.push(opts);
          return { ok: true };
        },
      },
    }).configRegeneration;
    assert.deepEqual(secondResult, { regenerated: true, restarted: true });
    assert.equal(secondRestarts.length, 1, 'the second launch actually retried the restart');
    assert.equal(JSON.parse(fs.readFileSync(files.manifestJson, 'utf8')).generated_by_version, '0.2.0');

    // Launch 3 — now settled, so it must stop retrying.
    const thirdRestarts = [];
    const thirdResult = await createEngineContext({
      ...deps(),
      pm2Control: {
        APP_NAME: 'litellm-nim',
        getStatus: async () => ({ status: 'running' }),
        startOrRestart: async (opts) => {
          thirdRestarts.push(opts);
          return { ok: true };
        },
      },
    }).configRegeneration;
    assert.deepEqual(thirdResult, { regenerated: false, reason: 'up-to-date' });
    assert.equal(thirdRestarts.length, 0);
  });
});

// ---------------------------------------------------------------------------
// NCOW-31 AC#1 — serialization, observed end to end through the real
// createEngineContext wiring (not just configGen's injected runner).
// ---------------------------------------------------------------------------

function deferred() {
  let resolve;
  const promise = new Promise((res) => {
    resolve = res;
  });
  return { promise, resolve };
}

test('createEngineContext: AC#1 — a user-initiated proxy op taking context.mutexes.proxy CANNOT interleave with the background regeneration restart', async () => {
  await withFakeHome(async (homeDir) => {
    seedStaleInstall(homeDir);
    const order = [];
    const restartGate = deferred();

    const pm2Control = {
      APP_NAME: 'litellm-nim',
      getStatus: async () => ({ status: 'running' }),
      startOrRestart: async () => {
        order.push('bg-restart:enter');
        // Stands in for startOrRestart()'s up-to-60s health-check window —
        // exactly the window NCOW-31 exists to cover.
        await restartGate.promise;
        order.push('bg-restart:exit');
        return { ok: true };
      },
      stop: async () => {
        order.push('user-stop:pm2.stop');
      },
    };

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger: recordingLogger(),
    });

    // Exactly how ipc.js invokes a mutating proxy handler: the real handler,
    // decorated with the real shared lock off the real context.
    const userStop = context.mutexes.proxy(async () => {
      order.push('user-stop:enter');
      return context.handlers.proxy.stop();
    })();

    // Wait for the restart to be genuinely in flight (a condition, not a fixed
    // number of microtask turns — the latter would make this test's *setup*
    // timing-sensitive), then let everything else that CAN progress, progress.
    while (!order.includes('bg-restart:enter')) await new Promise((r) => setImmediate(r));
    for (let i = 0; i < 20; i++) await Promise.resolve();

    assert.deepEqual(
      order,
      ['bg-restart:enter'],
      'the user Stop must be queued behind the in-flight background restart, not interleaved with it'
    );

    restartGate.resolve();
    const regen = await context.configRegeneration;
    await userStop;

    assert.deepEqual(regen, { regenerated: true, restarted: true });
    assert.deepEqual(order, [
      'bg-restart:enter',
      'bg-restart:exit',
      'user-stop:enter',
      'user-stop:pm2.stop',
    ]);
  });
});

test('createEngineContext: NCOW-31 fix pass 2 (reviewer finding B1) — the tray path (mutexes.proxy.run(...) wrapping handlers.proxy.*, the same shape tray.js\'s createTrayActions now wires into main/index.js\'s createTray({...})) also cannot interleave with the background regeneration restart', async () => {
  await withFakeHome(async (homeDir) => {
    seedStaleInstall(homeDir);
    const order = [];
    const restartGate = deferred();

    const pm2Control = {
      APP_NAME: 'litellm-nim',
      getStatus: async () => ({ status: 'running' }),
      startOrRestart: async () => {
        order.push('bg-restart:enter');
        // Stands in for startOrRestart()'s up-to-60s health-check window —
        // exactly the window NCOW-31 exists to cover.
        await restartGate.promise;
        order.push('bg-restart:exit');
        return { ok: true };
      },
      stop: async () => {
        order.push('tray-stop:pm2.stop');
      },
    };

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger: recordingLogger(),
    });

    // Before fix pass 2, main/index.js's createTray({ onStop }) called
    // handlers.proxy.stop() directly — no ipcMain, therefore no lock (see the
    // review's finding B1: tray.js only enables Stop/Restart when
    // status.status === 'running', which is exactly this restart's own
    // precondition). It now wraps every tray callback in
    // `mutexes.proxy.run(() => handlers.proxy.X())` via tray.js's exported
    // createTrayActions({ mutexes, handlers }) (NCOW-35) — the same primitive
    // registerIpcHandlers() decorates the IPC handlers with and
    // regenerateStaleConfig()'s own restart takes via `runProxyOperation`.
    // This reproduces that exact call shape off the real context (this file
    // cannot import tray.js itself: it requires('electron') at module scope,
    // which would poison the "pulls no electron into the module graph" test
    // further down in this same file/process). The behavioural proof against
    // the REAL createTrayActions — including identity with a real
    // ipc.js-registered handler and a negative control for the
    // nested-scope-shadowing mutation class review pass 2 identified — lives
    // in test/main/tray-actions.test.js, which is free to require tray.js
    // because it is its own file/process.
    const trayStop = context.mutexes.proxy.run(() => {
      order.push('tray-stop:enter');
      return context.handlers.proxy.stop();
    });

    // Wait for the restart to be genuinely in flight (a condition, not a fixed
    // number of microtask turns — the latter would make this test's *setup*
    // timing-sensitive), then let everything else that CAN progress, progress.
    while (!order.includes('bg-restart:enter')) await new Promise((r) => setImmediate(r));
    for (let i = 0; i < 20; i++) await Promise.resolve();

    assert.deepEqual(
      order,
      ['bg-restart:enter'],
      'the tray Stop must be queued behind the in-flight background restart, not interleaved with it'
    );

    restartGate.resolve();
    const regen = await context.configRegeneration;
    await trayStop;

    assert.deepEqual(regen, { regenerated: true, restarted: true });
    assert.deepEqual(order, [
      'bg-restart:enter',
      'bg-restart:exit',
      'tray-stop:enter',
      'tray-stop:pm2.stop',
    ]);
  });
});

test('createEngineContext: negative control — calling the handler with NO lock at all still interleaves, proving the assertion technique above would have caught a real race (not a false negative)', async () => {
  await withFakeHome(async (homeDir) => {
    seedStaleInstall(homeDir);
    const order = [];
    const restartGate = deferred();

    const pm2Control = {
      APP_NAME: 'litellm-nim',
      getStatus: async () => ({ status: 'running' }),
      startOrRestart: async () => {
        order.push('bg-restart:enter');
        await restartGate.promise;
        order.push('bg-restart:exit');
        return { ok: true };
      },
      stop: async () => {
        order.push('unlocked-stop:pm2.stop');
      },
    };

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger: recordingLogger(),
    });

    // Wait until the background restart is genuinely in flight, so "in the
    // middle" means exactly that.
    while (!order.includes('bg-restart:enter')) await new Promise((r) => setImmediate(r));

    // Deliberately bypasses BOTH locked call paths this task closes (ipc.js's
    // IPC-mediated handler above, and now main/index.js's tray wiring in the
    // test above) by invoking the raw handler with no lock in between at all.
    // This is not a description of any real call path left in the app after
    // fix pass 2 — every real caller now goes through one of the two locked
    // tests above. It exists purely so this suite proves its own
    // interleave-detection technique (wait for bg-restart:enter, then assert
    // `order`) actually catches a genuine race, ruling out the two tests above
    // passing merely because nothing in this test setup could ever interleave
    // regardless of locking.
    await context.handlers.proxy.stop();

    assert.deepEqual(
      order,
      ['bg-restart:enter', 'unlocked-stop:pm2.stop'],
      'called with no lock, the Stop lands in the middle of the restart — proving this test methodology would have caught the race the two locked tests above close'
    );
    assert.equal(order.includes('bg-restart:exit'), false, 'the restart really was still running when the Stop landed');

    restartGate.resolve();
    await context.configRegeneration;
  });
});

test('createEngineContext: the returned mutexes are the ones the regeneration restart actually takes (an injected set is honoured)', async () => {
  await withFakeHome(async (homeDir) => {
    seedStaleInstall(homeDir);
    const { createDomainMutexes } = require('../../src/main/mutex');
    const mutexes = createDomainMutexes();
    const order = [];
    const heldGate = deferred();

    // Hold the proxy lock BEFORE createEngineContext even runs. If its
    // regeneration restart takes this same lock, the restart cannot start until
    // this releases.
    const preHeld = mutexes.proxy.run(async () => {
      order.push('pre-held:enter');
      await heldGate.promise;
      order.push('pre-held:exit');
    });

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      mutexes,
      pm2Control: {
        APP_NAME: 'litellm-nim',
        getStatus: async () => {
          order.push('bg:getStatus');
          return { status: 'running' };
        },
        startOrRestart: async () => {
          order.push('bg:startOrRestart');
          return { ok: true };
        },
      },
      logger: recordingLogger(),
    });

    assert.equal(context.mutexes, mutexes, 'the context must expose the very same set it uses');

    for (let i = 0; i < 20; i++) await Promise.resolve();
    assert.deepEqual(order, ['pre-held:enter'], 'the background restart must be blocked by the pre-held lock');
    assert.equal(order.includes('bg:getStatus'), false, 'not even the status read may happen inside someone else\'s critical section');

    heldGate.resolve();
    await preHeld;
    await context.configRegeneration;
    assert.deepEqual(order, ['pre-held:enter', 'pre-held:exit', 'bg:getStatus', 'bg:startOrRestart']);
  });
});

// NCOW-31: the constraint that forced the mutex primitive into its own module
// in the first place (see src/main/mutex.js's header). engine-context.js is
// required at the top of THIS file, and every other suite that touches it,
// under plain `node --test` with no Electron runtime — so nothing it pulls in
// transitively may require('electron') at module scope. mutex.js is the new
// edge in that graph; if it ever grows an electron import, roughly a third of
// this repo's suites break at require time and this test says why.
test('engine-context.js: requiring it (and therefore mutex.js) pulls no electron into the module graph', () => {
  assert.ok(require('../../src/main/engine-context').createEngineContext);
  assert.ok(require('../../src/main/mutex').createDomainMutexes);
  const electronEntries = Object.keys(require.cache).filter((k) => /[/\\]node_modules[/\\]electron[/\\]/.test(k));
  assert.deepEqual(electronEntries, []);
});

// index.js itself can't be required under plain `node --test` (it touches
// electron.app at module scope) — mirrors auto-update-wiring.test.js's
// static source-check approach for the same reason.
test('index.js: a failed configRegeneration is logged, not silently dropped', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', '..', 'src', 'main', 'index.js'), 'utf8');
  assert.match(source, /const \{ handlers, pm2Control, configRegeneration, mutexes \} = createEngineContext/);
  assert.match(source, /configRegeneration[\s\S]{0,200}console\.warn/, 'expected configRegeneration to be observed and logged on failure');
});

// NCOW-31 fix pass 2 (reviewer finding B1) / NCOW-35: the tray's
// Start/Stop/Restart used to call handlers.proxy.* directly, bypassing
// ipcMain and therefore the mutex entirely. The original fix inlined
// `onStart: () => mutexes.proxy.run(() => handlers.proxy.start())` etc.
// straight into index.js's createTray({...}) call, provable only by a
// source-text regex over index.js — review pass 2 found that regex has a real
// identity gap: it only checks that the text `mutexes.proxy.run(...)` appears
// at the call site, not that `mutexes` resolves to the SAME lock instance
// ipc.js and engine-context.js use, so a mutation shadowing `mutexes` in a
// nested scope right around this call (giving the tray its own private,
// unshared lock) still passed every test that regex could offer.
//
// NCOW-35 pulls that wiring into tray.js's exported createTrayActions({
// mutexes, handlers }) instead (mirroring menu.js's buildMenuTemplate). The
// identity proof — that the tray, ipc.js, and engine-context.js all contend
// for one shared mutex instance, and that a shadowed/private set is
// detectably different — is now a BEHAVIOURAL test against the real seam, in
// test/main/tray-actions.test.js.
//
// NCOW-35 fix pass (mandatory review): that behavioural test, and the
// call-site regex below, each reach only part of the chain. The behavioural
// test proves createTrayActions({ mutexes, handlers }) shares a lock with
// ipc.js/engine-context.js whenever it is invoked with the SAME `mutexes`
// binding — but it imports tray.js directly and cannot see what identifier
// index.js itself passes in. The call-site regex below only confirms the
// text `...createTrayActions({ mutexes, handlers })` appears inside the
// createTray({...}) call; it is blind to whether `mutexes` resolves to the
// shared instance or a private one, exactly as review pass 2's original
// `mutexes.proxy.run(...)` regex was. A nested block scope wrapped around
// createTray({...}) that shadows `mutexes` with its own
// `require('./mutex').createDomainMutexes()` right before spreading it in
// passes both checks and still leaves the tray fully unlocked — this was
// reproduced against a real reviewer pass and confirmed to slip through
// npm test unnoticed.
//
// index.js itself can't be required under plain `node --test` (electron.app
// at module scope), so this file closes THAT gap with a second, file-wide
// static check just below: that the `mutexes` identifier is bound exactly
// once anywhere in index.js — the createEngineContext() destructure at the
// top of whenReady() — with no other declaration and no bare reassignment.
// "Is this identifier rebound or re-declared anywhere in this file" is a
// source property a static check can legitimately settle, unlike "does this
// lock actually serialize" (which only the behavioural test can reach).
//
// NCOW-35 review (NCOW-39 follow-up, fix pass 2): together these two checks
// prove something narrower than earlier wording here claimed. The
// behavioural test (test/main/tray-actions.test.js) proves
// createTrayActions({ mutexes, handlers }) serializes through WHATEVER
// mutex set it is handed, with a negative control confirming that an
// externally-provided, differing mutex set — a parameter passed IN to
// createTrayActions, not one it constructs itself — fails the test — but it
// imports tray.js directly, so it says nothing about what index.js itself
// passes in. The static check just below proves only that the `mutexes`
// identifier — specifically `mutexes`, not `handlers` — is declared/bare-
// reassigned exactly once anywhere in index.js. Neither check, nor the pair
// together, closes the full chain; three further gaps were identified here:
//
// - `handlers` had no equivalent single-binding check at all. The static
//   check's one mention of `handlers` only confirmed that mutexes' sole
//   declaration happens to be the
//   `const { handlers, pm2Control, configRegeneration, mutexes } =`
//   destructure — it did nothing to forbid a SECOND, shadowing `handlers`
//   binding wrapped around createTray({...}), giving the tray a private,
//   unshared `handlers`. (Confirmed: wrapping the createTray({...}) call in
//   a nested block that declares its own private
//   `const handlers = { proxy: {...} }` passed the full suite.)
// - Property-level mutation of `mutexes.proxy` (e.g. reassigning it to a
//   fresh `createDomainMutex()` between registerIpcHandlers() and
//   createTray({...})) is invisible to both checks — `mutexes` is still
//   declared exactly once and the spread text is still present verbatim —
//   yet NCOW-35's own review verified this is a REAL serialization break
//   (tray Stop ran while an IPC restart was still in-flight), and it passed
//   the full suite anyway.
// - Parameter shadowing, e.g. wrapping the whole call as
//   `((mutexes) => createTray({ ...createTrayActions({ mutexes, handlers })
//   }))(privateMutexSet)`, is the same nested-scope-shadowing class the
//   static check exists to catch, just introduced via a function parameter
//   instead of a declaration or reassignment — also passed the full suite.
//
// Two of the three are reachable by the same single-binding technique
// already used for `mutexes`. `handlers` turned out to need exactly that —
// it simply didn't have one yet — and so did parameter shadowing: it is the
// same nested-scope-shadowing class the declaration/reassignment checks
// already covered, just arriving via a third JS binding mechanism (a
// parameter) instead of a `const` re-declaration or a bare reassignment, and
// a text-only regex can see a parameter list exactly as well as it can see a
// declaration. Both are folded into the identifier-binding tests below.
//
// NCOW-41 fix pass (reviewer finding): property-level mutation of
// `mutexes.proxy` (or `handlers.proxy`) was FIRST assumed to be different in
// kind — the claim briefly written here was that nothing about the
// *identifier* changes, so no source-text scan could distinguish a
// legitimate read (`mutexes.proxy.run(...)`) from a mutation. That claim was
// wrong and was disproven during review: the legitimate read is a
// member-access-then-call with no `=` anywhere in it, while a mutation is
// exactly `identifier.prop = ...` (or the computed-key form
// `identifier['prop'] = ...`) followed by a single `=`, never `==`/`===`.
// That is a source-text property a regex can and does settle —
// identifierPropertyIsAssigned() below — with no false positive on the real
// `mutexes.proxy.run(() => handlers.proxy.stop())` call site and a true
// positive on the exact mutation NCOW-35's review verified as a real
// serialization break. The behavioural regression test in
// test/main/tray-actions.test.js stays as "why this matters" documentation —
// it reproduces the mutation against the real
// createTrayActions/registerIpcHandlers/mutex.js primitives and shows the
// two callers stop sharing a lock — but the AC#2 guard itself is this
// text-only check, not that behavioural test alone.
//
// A fourth gap — a plain object literal override, where a future edit adds
// its own `onStart`/`onStop`/`onRestart` key to the createTray({...}) object
// literal AFTER the `...createTrayActions({ mutexes, handlers })` spread, so
// plain JS object semantics let that later key silently win and discard the
// mutex-wrapped action the spread contributed, with `mutexes` still bound
// exactly once and the spread text still present verbatim so neither check
// above would notice — was addressed by NCOW-38, which added two further
// tests below (after the identifier-binding check that follows this
// comment): one that extracts this same createTray({...}) block, locates
// the createTrayActions(...) spread, and fails if an onStart/onStop/
// onRestart key appears anywhere in the text after it; and a meta-test that
// reproduces this exact shape — a key hand-added after the spread in a
// synthetic createTray({...}) block — and confirms the guard actually
// catches it, rather than merely existing unexercised. That guard was not
// actually closed by NCOW-38's landing, though: a later review (folded into
// this task, NCOW-41) found its detector, findKeyAfterTraySpread(), was
// fail-open rather than fail-loud — it returned `undefined` both when no
// override existed AND when the `...createTrayActions` spread wasn't found
// in the extracted block at all (e.g. a nested `});` between the spread and
// an override key truncating the block early), so the exact regression this
// guard exists to catch could slip through green in that shape. NCOW-41
// fixes that (the detector now throws if it never locates the spread, rather
// than returning the same `undefined` as "nothing followed it"), and widens
// the override-key regex itself to also catch quoted keys, method
// shorthand, and computed keys, not just the file's one-key-per-line
// bare-colon style. With both of those landed, this fourth gap is now
// genuinely closed.
//
// Equivalent guards for the three gaps described above — `handlers`'
// missing single-binding check, `mutexes`/`handlers` property-level
// mutation, and parameter shadowing — are added by NCOW-41 too: see the
// identifier-binding tests immediately below for all three. The
// property-mutation guard turned out to be exactly as reachable by a
// text-only check as the other two (identifierPropertyIsAssigned(), added in
// this task's fix pass — see the comment above for what changed and why);
// test/main/tray-actions.test.js's existing behavioural test is kept
// alongside it as "why this matters" proof of the mutation's real-world
// impact, not as the sole guard against it. Together, this file's static
// checks and tray-actions.test.js's behavioural proof now cover every
// tray-wiring identity gap identified across NCOW-35/38/39/41's reviews of
// this one call site — a description of how thoroughly THIS seam has been
// reviewed, not a general claim that tray wiring (or this app) has been
// proven safe end to end.
test('index.js: createTray({...}) is wired with tray.js\'s createTrayActions({ mutexes, handlers }), using the context\'s own mutexes/handlers', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', '..', 'src', 'main', 'index.js'), 'utf8');
  assert.match(
    source,
    /const \{ createTray, createTrayActions \} = require\(['"]\.\/tray['"]\)/,
    'expected index.js to import createTrayActions alongside createTray from tray.js'
  );

  const trayCallAt = source.indexOf('createTray({');
  assert.ok(trayCallAt > -1, 'expected to find the createTray({...}) call');
  const trayCallEnd = source.indexOf('});', trayCallAt);
  assert.ok(trayCallEnd > -1, 'expected the createTray({...}) call to close with });');
  const trayBlock = source.slice(trayCallAt, trayCallEnd);

  assert.match(
    trayBlock,
    /\.\.\.createTrayActions\(\{\s*mutexes,\s*handlers\s*\}\)/,
    'createTray({...}) must spread createTrayActions({ mutexes, handlers }) in, using those exact bindings'
  );
});

// NCOW-35 fix pass (mandatory review, finding F1): the check above is a
// call-site regex — it cannot tell a genuinely shared `mutexes` from one
// shadowed by a nested block scope wrapped around the whole createTray({...})
// call, e.g.:
//
//   let tray;
//   {
//     const mutexes = require('./mutex').createDomainMutexes();
//     tray = createTray({ ...createTrayActions({ mutexes, handlers }) });
//   }
//
// That reproduces the exact mutation class review pass 2 identified for the
// old inline `mutexes.proxy.run(...)` wiring — the identity gap didn't close
// when that wiring moved into createTrayActions(), it just moved with it —
// and it passed the call-site regex (and the full suite) before this test
// existed. Checking "is `mutexes` rebound or re-declared anywhere in this
// file" is something a static check CAN legitimately settle (unlike lock
// behaviour), so this asserts index.js binds the identifier exactly once —
// the createEngineContext() destructure — with no shadowing re-declaration
// and no bare reassignment anywhere else in the file.
/**
 * NCOW-41: a third JS binding mechanism the declaration/bare-reassignment
 * checks below cannot see — a function PARAMETER with this name, e.g.
 * `((mutexes) => createTray({...}))(privateMutexSet)` or the unparenthesized
 * single-arrow-param form `mutexes => ...`. This is the same
 * nested-scope-shadowing class NCOW-35's review identified for `mutexes`,
 * just introduced via a parameter instead of a `const` re-declaration or a
 * bare reassignment — and it is just as invisible to the call-site regex and
 * the "spread text still present verbatim" check as those originally were.
 *
 * Deliberately regex-based, matching every other static check in this file
 * (no parser dependency is available in this repo's devDependencies — see
 * package.json). `[^()]*` for a parameter list is enough for this file's own
 * arrow-function style (plain identifiers, no nested-paren defaults) and for
 * the synthetic strings the meta-test below builds.
 */
function identifierBoundAsFunctionParam(source, identifier) {
  const paramLists = [];

  const arrowWithParens = /\(([^()]*)\)\s*=>/g;
  let m;
  while ((m = arrowWithParens.exec(source))) paramLists.push(m[1]);

  const namedFunction = /\bfunction\b[^(]*\(([^()]*)\)/g;
  while ((m = namedFunction.exec(source))) paramLists.push(m[1]);

  const boundByList = paramLists.some((params) =>
    params
      .split(',')
      .map((p) => p.trim().replace(/^\.\.\./, '').split(/[\s=]/)[0])
      .includes(identifier)
  );
  if (boundByList) return true;

  // The unparenthesized single-arrow-param form (`identifier => ...`) has no
  // enclosing `(...)` for the pattern above to find.
  const bareArrowParam = new RegExp(`(?<![\\w$])${identifier}(?![\\w$])\\s*=>`);
  return bareArrowParam.test(source);
}

/**
 * NCOW-41 fix pass (AC#2, reviewer finding): catches property-level mutation
 * of `mutexes.proxy` (or the equivalent `handlers.*` property) — reassigning
 * a PROPERTY of the shared object, rather than rebinding the identifier
 * itself, which is what the declaration/reassignment/parameter checks above
 * each target. `mutexes` (or `handlers`) stays declared exactly once and the
 * `...createTrayActions({ mutexes, handlers })` spread text stays present
 * verbatim, so none of those checks notice — but NCOW-35's own review
 * empirically verified this is a REAL serialization break (a tray Stop ran
 * concurrently with an in-flight IPC-triggered restart), and it passed the
 * full suite regardless, until now.
 *
 * A first draft of the comment above this function's call sites claimed this
 * gap was outside a text-only check's reach entirely — a legitimate read
 * (`mutexes.proxy.run(...)`) and a mutation (`mutexes.proxy = ...`) supposedly
 * looked too similar for a regex to tell apart. That claim was wrong: a read
 * is a member access immediately followed by `(` or `.` — never `=` — while
 * an assignment is the property access followed by exactly one `=` (not `==`
 * or `===`). That is a source-text distinction, not a runtime one, so a
 * regex settles it exactly as it settles the declaration/reassignment checks
 * above. Verified against the real index.js (no match — nothing here
 * mutates a property of either identifier), the exact mutation NCOW-35's
 * review reproduced (`mutexes.proxy = require('./mutex').createDomainMutex()`,
 * matched), and the real call site's own
 * `mutexes.proxy.run(() => handlers.proxy.stop())` read (not matched).
 */
function identifierPropertyIsAssigned(source, identifier) {
  const pattern = new RegExp(`\\b${identifier}\\s*(?:\\.[A-Za-z_$][\\w$]*|\\[[^\\]]*\\])\\s*=(?!=)`);
  return pattern.test(source);
}

test('index.js: the `mutexes` identifier is bound exactly once (the createEngineContext() destructure), with no shadowing re-declaration, bare reassignment, parameter binding, or property mutation anywhere else in the file', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', '..', 'src', 'main', 'index.js'), 'utf8');

  // Every place `mutexes` is *bound* to a value via a declaration keyword:
  // the bare form (`const mutexes = ...`) or the destructured form
  // (`const { ..., mutexes, ... } = ...`).
  const declarationPattern = /\b(?:const|let|var)\s+(?:\{[^{}]*\bmutexes\b[^{}]*\}|mutexes\b)\s*=/g;
  const declarations = source.match(declarationPattern) ?? [];
  assert.equal(
    declarations.length,
    1,
    `expected exactly one declaration binding "mutexes" in index.js (the createEngineContext() destructure), found ${declarations.length}: ${JSON.stringify(declarations)}`
  );
  assert.match(
    declarations[0],
    /const \{ handlers, pm2Control, configRegeneration, mutexes \}\s*=$/,
    'the sole "mutexes" binding must be the createEngineContext() destructure, not some other declaration'
  );

  // A bare reassignment (`mutexes = ...`, no declaration keyword) rebinds the
  // identifier just as effectively as a shadowing re-declaration, and is
  // equally invisible to a regex scoped to the createTray({...}) call site.
  const bareAssignmentPattern = /(?<!(?:const|let|var)\s+)\bmutexes\s*=(?!=)/g;
  const bareAssignments = source.match(bareAssignmentPattern) ?? [];
  assert.equal(
    bareAssignments.length,
    0,
    `expected no bare "mutexes = ..." reassignment anywhere in index.js, found: ${JSON.stringify(bareAssignments)}`
  );

  // NCOW-41 (AC#3): a function parameter named `mutexes` shadows the shared
  // binding just as effectively as the two mechanisms above, via a third JS
  // binding form neither of them can see.
  assert.equal(
    identifierBoundAsFunctionParam(source, 'mutexes'),
    false,
    'expected "mutexes" never to appear as a function parameter name in index.js — a wrapping function ' +
      'like "((mutexes) => createTray({...}))(privateSet)" would shadow the shared binding via a ' +
      'parameter instead of a declaration or reassignment, evading both checks above'
  );

  // NCOW-41 fix pass (AC#2, reviewer finding): mutating a PROPERTY of the
  // shared `mutexes` (e.g. `mutexes.proxy = require('./mutex').createDomainMutex()`
  // between the createEngineContext() destructure and createTray({...}))
  // shadows the shared lock just as effectively as the three checks above,
  // without rebinding the identifier itself at all — see
  // identifierPropertyIsAssigned()'s own comment for why this is reachable
  // by a text-only check, contrary to what an earlier draft of the big
  // review comment above claimed.
  assert.equal(
    identifierPropertyIsAssigned(source, 'mutexes'),
    false,
    'expected no "mutexes.<property> = ..." or "mutexes[\'<property>\'] = ..." assignment anywhere in ' +
      'index.js — mutating a property of the shared mutexes object (e.g. reassigning mutexes.proxy to a ' +
      'fresh lock) breaks serialization exactly as a shadowing rebind would, and NCOW-35\'s review verified ' +
      'this is a real regression, not a theoretical one'
  );
});

// NCOW-41 (AC#1): `handlers` gets the exact same four-way single-binding
// check `mutexes` already had above — it was exactly as reachable by these
// techniques, it simply didn't have a test yet. Before this test existed,
// wrapping createTray({...}) in a nested block that declared its own
// private `const handlers = { proxy: {...} }` passed the full suite,
// silently giving the tray a private, unshared `handlers` (confirmed during
// NCOW-39's review).
test('index.js: the `handlers` identifier is bound exactly once (the createEngineContext() destructure), with no shadowing re-declaration, bare reassignment, parameter binding, or property mutation anywhere else in the file', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', '..', 'src', 'main', 'index.js'), 'utf8');

  const declarationPattern = /\b(?:const|let|var)\s+(?:\{[^{}]*\bhandlers\b[^{}]*\}|handlers\b)\s*=/g;
  const declarations = source.match(declarationPattern) ?? [];
  assert.equal(
    declarations.length,
    1,
    `expected exactly one declaration binding "handlers" in index.js (the createEngineContext() destructure), found ${declarations.length}: ${JSON.stringify(declarations)}`
  );
  assert.match(
    declarations[0],
    /const \{ handlers, pm2Control, configRegeneration, mutexes \}\s*=$/,
    'the sole "handlers" binding must be the createEngineContext() destructure, not some other declaration'
  );

  const bareAssignmentPattern = /(?<!(?:const|let|var)\s+)\bhandlers\s*=(?!=)/g;
  const bareAssignments = source.match(bareAssignmentPattern) ?? [];
  assert.equal(
    bareAssignments.length,
    0,
    `expected no bare "handlers = ..." reassignment anywhere in index.js, found: ${JSON.stringify(bareAssignments)}`
  );

  assert.equal(
    identifierBoundAsFunctionParam(source, 'handlers'),
    false,
    'expected "handlers" never to appear as a function parameter name in index.js — a wrapping function ' +
      'like "((handlers) => createTray({...}))(privateSet)" would shadow the shared binding via a ' +
      'parameter instead of a declaration or reassignment, evading the two checks above'
  );

  // NCOW-41 fix pass (AC#2, reviewer finding): the `handlers` equivalent of
  // the `mutexes.proxy` mutation check above — see that assertion's comment
  // and identifierPropertyIsAssigned()'s own comment for why this is
  // reachable by a text-only check.
  assert.equal(
    identifierPropertyIsAssigned(source, 'handlers'),
    false,
    'expected no "handlers.<property> = ..." or "handlers[\'<property>\'] = ..." assignment anywhere in ' +
      'index.js — mutating a property of the shared handlers object shadows it exactly as a shadowing ' +
      'rebind would, evading the checks above'
  );
});

// NCOW-41: proves identifierBoundAsFunctionParam() (used by both tests
// above) actually catches the parameter-shadowing shape it targets, against
// synthetic source rather than today's already-correct index.js — mirroring
// findKeyAfterTraySpread()'s own meta-test further down in this file. Per
// task guidance, this is what makes AC#3 a genuine regression test rather
// than a check that merely happens to pass today: reverting this meta-test's
// assertions to their pre-NCOW-41 (nonexistent) state would leave no test in
// this suite able to distinguish the "bad" blocks below from safe code.
test('index.js: the parameter-binding check (used by the mutexes/handlers single-binding tests above) actually catches the shape it targets (meta-test)', () => {
  const goodSource = 'const tray = createTray({ ...createTrayActions({ mutexes, handlers }) });';
  for (const identifier of ['mutexes', 'handlers']) {
    assert.equal(
      identifierBoundAsFunctionParam(goodSource, identifier),
      false,
      'sanity check: real-shaped code with no parameter binding must not be flagged'
    );

    const wrappedWithParens = `((${identifier}) => createTray({ ...createTrayActions({ mutexes, handlers }) }))(privateSet);`;
    assert.equal(
      identifierBoundAsFunctionParam(wrappedWithParens, identifier),
      true,
      `expected to catch "${identifier}" reintroduced as a wrapping function parameter (parenthesized form)`
    );

    const wrappedBare = `${identifier} => createTray({ ...createTrayActions({ mutexes, handlers }) });`;
    assert.equal(
      identifierBoundAsFunctionParam(wrappedBare, identifier),
      true,
      `expected to catch "${identifier}" reintroduced as a wrapping function parameter (unparenthesized form)`
    );

    const namedFunctionWrapper = `function withPrivate(${identifier}) { return createTray({ ...createTrayActions({ mutexes, handlers }) }); }`;
    assert.equal(
      identifierBoundAsFunctionParam(namedFunctionWrapper, identifier),
      true,
      `expected to catch "${identifier}" reintroduced as a named function's parameter`
    );
  }
});

// NCOW-41 fix pass (AC#2, reviewer finding): proves
// identifierPropertyIsAssigned() (used by both single-binding tests above)
// actually catches the property-mutation shape it targets, against
// synthetic source, AND does not flag the real call site's own legitimate
// read — mirroring the parameter-binding meta-test above and
// findKeyAfterTraySpread()'s own meta-test further down in this file. This
// is what makes the AC#2 assertions above a genuine regression test rather
// than a check that merely happens to pass today: without this meta-test,
// nothing in this suite would distinguish the "bad" (mutating) strings below
// from the "good" (reading) one, so a future edit could silently weaken
// identifierPropertyIsAssigned() back into a no-op and every single-binding
// test above would keep passing regardless.
test('index.js: the property-mutation check (used by the mutexes/handlers single-binding tests above) actually catches the shape it targets, without flagging the real call site\'s legitimate mutexes.proxy.run(...)/handlers.proxy.stop() read (meta-test)', () => {
  const legitimateRead = 'mutexes.proxy.run(() => handlers.proxy.stop())';
  for (const identifier of ['mutexes', 'handlers']) {
    assert.equal(
      identifierPropertyIsAssigned(legitimateRead, identifier),
      false,
      `sanity check: the real call site's legitimate "${identifier}.proxy...()" read must not be flagged as a mutation`
    );

    const equalityCheck = `if (${identifier}.proxy === someOtherMutex) {}`;
    assert.equal(
      identifierPropertyIsAssigned(equalityCheck, identifier),
      false,
      `sanity check: an equality comparison ("${identifier}.proxy === ...") must not be flagged as an assignment`
    );

    const spreadRead = `const x = { ...${identifier}.app, quit: 1 };`;
    assert.equal(
      identifierPropertyIsAssigned(spreadRead, identifier),
      false,
      `sanity check: spreading a property ("...${identifier}.app") must not be flagged as an assignment`
    );

    const dotMutation = `${identifier}.proxy = require('./mutex').createDomainMutex();`;
    assert.equal(
      identifierPropertyIsAssigned(dotMutation, identifier),
      true,
      `expected to catch "${identifier}.proxy" reassigned via dot-property mutation — this is the exact ` +
        "shape NCOW-35's review reproduced as a real serialization break"
    );

    const computedMutation = `${identifier}['proxy'] = require('./mutex').createDomainMutex();`;
    assert.equal(
      identifierPropertyIsAssigned(computedMutation, identifier),
      true,
      `expected to catch "${identifier}['proxy']" reassigned via computed-property mutation`
    );
  }
});

// NCOW-38: closes the "plain object literal override" gap identified in the
// big review comment above — a future edit that adds its own
// onStart/onStop/onRestart key to the createTray({...}) object literal AFTER
// the ...createTrayActions({ mutexes, handlers }) spread would silently win
// by plain JS object-literal semantics, discarding the mutex-wrapped action
// the spread contributed and reintroducing an unserialized tray action
// racing the shared proxy mutex (NCOW-31 finding B1) — with `mutexes` still
// bound exactly once and the spread text still present verbatim, so neither
// the call-site regex nor the identifier-binding check above would notice.
//
// Extracted as a standalone helper (rather than inlined in the test below)
// so the meta-test immediately following it can apply the EXACT same
// detection logic to a hand-built reproduction of the bad shape, rather than
// asserting on a second, potentially-drifted copy of the regex.
//
// NCOW-41 (AC#6): widened from the original bare-colon-only form
// (`onStop: ...`) to also catch a quoted key (`'onStop': ...`), method
// shorthand (`onStop() {...}`, including `async onStop() {...}`), and a
// computed key (`['onStop']: ...`) — index.js's own style only ever uses the
// bare-colon form today, but an override introduced any of these other ways
// is exactly as real a regression and was previously invisible to this
// guard.
//
// NCOW-41 (AC#7, fail-loud fix): before this, the function returned
// `undefined` both when no override key existed AND when the
// `...createTrayActions` spread was never found in the supplied block at
// all — e.g. because the caller's own `indexOf('});')` extraction hit a
// NESTED `});` between the spread and an override key, truncating the block
// before the spread text ever appears. Both cases produced the identical
// `undefined` the guard test below treats as "safe", so the exact
// regression this guard exists to catch could slip through green in that
// shape without anyone noticing the block had been cut short before it ever
// saw the spread. Throwing here instead makes that distinction impossible
// to miss: no caller can reach "no override key found" without the spread
// having first been genuinely located.
function findKeyAfterTraySpread(trayBlock) {
  const spreadMatch = trayBlock.match(/\.\.\.createTrayActions\(\{\s*mutexes,\s*handlers\s*\}\)/);
  if (!spreadMatch) {
    throw new Error(
      'findKeyAfterTraySpread(): no `...createTrayActions({ mutexes, handlers })` spread found in the ' +
        'supplied block. This is fail-loud on purpose (NCOW-41): returning undefined here would be ' +
        'indistinguishable from "the spread was found and nothing followed it", which is exactly the ' +
        'condition the post-spread-override guard treats as safe. If this fired against index.js\'s real ' +
        'createTray({...}) block, the block was likely truncated before the spread — check the caller\'s ' +
        'own indexOf(\'});\') extraction for a nested closing "});" between "createTray({" and the spread.'
    );
  }
  const afterSpread = trayBlock.slice(spreadMatch.index + spreadMatch[0].length);
  // One property per line is this file's (and index.js's) consistent style,
  // so anchoring the key to the start of a line — rather than matching it
  // anywhere in the text — is enough to find a real object-literal key
  // without also tripping on the word appearing inside a comment. The four
  // alternatives below cover every way JS lets an object literal (or class-
  // like method block) introduce one of these three key names: bare colon,
  // quoted-string colon, computed (bracketed) colon, and method shorthand
  // (optionally `async`).
  const KEYS = 'onStart|onStop|onRestart';
  const overrideKeyPattern = new RegExp(
    `^\\s*(?:` +
      `(?:async\\s+)?(${KEYS})\\s*\\(` + // method shorthand: onStop() {...} / async onStop() {...}
      `|(${KEYS})\\s*:` + // bare colon: onStop: ...
      `|['"](${KEYS})['"]\\s*:` + // quoted key: 'onStop': ... / "onStop": ...
      `|\\[\\s*['"](${KEYS})['"]\\s*\\]\\s*:` + // computed key: ['onStop']: ...
      `)`,
    'm'
  );
  const match = afterSpread.match(overrideKeyPattern);
  return match ? match[1] || match[2] || match[3] || match[4] : undefined;
}

test('index.js: createTray({...}) defines no onStart/onStop/onRestart key AFTER the createTrayActions(...) spread (post-spread override guard)', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', '..', 'src', 'main', 'index.js'), 'utf8');
  const trayCallAt = source.indexOf('createTray({');
  assert.ok(trayCallAt > -1, 'expected to find the createTray({...}) call');
  const trayCallEnd = source.indexOf('});', trayCallAt);
  assert.ok(trayCallEnd > -1, 'expected the createTray({...}) call to close with });');
  const trayBlock = source.slice(trayCallAt, trayCallEnd);

  // NCOW-41 (AC#7): explicit, ahead of the real assertion below, that the
  // spread was actually located inside the extracted block — the naive
  // indexOf('});') extraction above stops at the FIRST "});" after
  // "createTray({", so a nested one (e.g. inside a future callback added to
  // this object literal) would silently truncate trayBlock before the
  // spread ever appears. findKeyAfterTraySpread() itself now throws in that
  // case rather than returning the same `undefined` as "nothing followed
  // the spread" — this assertion documents why that distinction is checked
  // at all, right where a failure here would otherwise look identical to
  // the guard just passing.
  assert.match(
    trayBlock,
    /\.\.\.createTrayActions\(\{\s*mutexes,\s*handlers\s*\}\)/,
    'expected the extracted createTray({...}) block to actually contain the createTrayActions(...) spread ' +
      '— if this fails, the block was truncated before ever reaching it (see the comment on ' +
      'findKeyAfterTraySpread() above), and the assertion below would otherwise pass for the wrong reason'
  );

  const overriddenKey = findKeyAfterTraySpread(trayBlock);
  assert.equal(
    overriddenKey,
    undefined,
    `found "${overriddenKey}" defined after the ...createTrayActions({ mutexes, handlers }) spread inside ` +
      'createTray({...}) — plain JS object-literal semantics let this later key silently discard the ' +
      'mutex-wrapped action the spread contributed, reintroducing an unserialized tray action racing the ' +
      'shared proxy mutex (NCOW-31 finding B1). Move it before the spread, or fold the behaviour into ' +
      "tray.js's createTrayActions() itself."
  );
});

// NCOW-38 (AC#2): the guard above is only as good as its ability to actually
// catch the shape it targets. This applies the exact same
// findKeyAfterTraySpread() detection logic to synthetic createTray({...})
// blocks that reproduce the "key added after the spread" shape precisely —
// proving the guard would fail on a real regression, not just that it
// currently passes on today's (already-correct) index.js for some unrelated
// reason.
//
// NCOW-41 (AC#6): extended beyond the original bare-colon-only cases to also
// cover a quoted key, method shorthand (plain and async), and a computed
// key — the three additional forms the widened regex in
// findKeyAfterTraySpread() now catches.
test('index.js: the post-spread-override guard actually catches the regression shape it targets (meta-test)', () => {
  const goodBlock = `createTray({
      showDashboard: () => showMainWindow('dashboard'),
      showDiagnostics: () => showMainWindow('diagnostics'),
      quit: () => app.quit(),
      ...createTrayActions({ mutexes, handlers }),
    });`;
  assert.equal(
    findKeyAfterTraySpread(goodBlock),
    undefined,
    'sanity check: a spread with nothing after it in the same object literal must not be flagged'
  );

  const overrideForms = {
    'bare colon': (key) => `${key}: () => handlers.proxy.stop(),`,
    'single-quoted key': (key) => `'${key}': () => handlers.proxy.stop(),`,
    'double-quoted key': (key) => `"${key}": () => handlers.proxy.stop(),`,
    'method shorthand': (key) => `${key}() { return handlers.proxy.stop(); },`,
    'async method shorthand': (key) => `async ${key}() { return handlers.proxy.stop(); },`,
    'computed key (single-quoted)': (key) => `['${key}']: () => handlers.proxy.stop(),`,
    'computed key (double-quoted)': (key) => `["${key}"]: () => handlers.proxy.stop(),`,
  };

  for (const key of ['onStart', 'onStop', 'onRestart']) {
    for (const [formName, buildLine] of Object.entries(overrideForms)) {
      const badBlock = `createTray({
      showDashboard: () => showMainWindow('dashboard'),
      showDiagnostics: () => showMainWindow('diagnostics'),
      quit: () => app.quit(),
      ...createTrayActions({ mutexes, handlers }),
      ${buildLine(key)}
    });`;
      assert.equal(
        findKeyAfterTraySpread(badBlock),
        key,
        `expected the guard to catch a literal "${key}" key (${formName} form) hand-added after the ` +
          'createTrayActions(...) spread'
      );
    }
  }
});

// NCOW-41 (AC#7): proves the fail-loud fix itself — a block that never
// contains the createTrayActions(...) spread at all (standing in for the
// truncation scenario described on findKeyAfterTraySpread() above: a nested
// "});" between the spread and an override key cutting the extracted block
// short before the spread text ever appears) must throw, not silently
// return the same `undefined` a spread-with-no-override-after-it would.
// Before this fix, both shapes were indistinguishable from inside the
// guard test, so the exact regression the guard exists to catch could slip
// through green.
test('index.js: findKeyAfterTraySpread() fails loud (throws) when the spread is not found, rather than returning the same undefined as "no override" (meta-test)', () => {
  const truncatedBlock = `createTray({
      showDashboard: () => showMainWindow('dashboard'),
      onSomethingElse: () => {
        doSomethingWith(() => {
          finish();
        });
      });`;
  assert.doesNotMatch(
    truncatedBlock,
    /\.\.\.createTrayActions\(\{\s*mutexes,\s*handlers\s*\}\)/,
    'sanity check: this block must genuinely lack the spread, matching what a nested "});" truncation would produce'
  );
  assert.throws(
    () => findKeyAfterTraySpread(truncatedBlock),
    /no `\.\.\.createTrayActions/,
    'expected findKeyAfterTraySpread() to throw rather than silently report "no override found" for a ' +
      'block that never contained the spread at all'
  );
});
