'use strict';

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const { createEngineContext } = require('../../src/main/engine-context');
const { generateAll } = require('../../src/engine/configGen');
const paths = require('../../src/engine/paths');

// Mirrors test/main/engine-context-apikey.test.js's / engine-context-config-regen.test.js's
// withFakeHome — the only sanctioned way (per CLAUDE.md) to point
// createEngineContext() at a throwaway directory instead of this machine's
// real ~/.config/claude-conduit.
function withFakeHome(fn) {
  const homeDir = fs.mkdtempSync(path.join(os.tmpdir(), 'nim-engine-context-connmig-test-'));
  const argvHadDev = process.argv.includes('--dev');
  const originalTestHome = process.env.NIM_PROXY_TEST_HOME;
  if (!argvHadDev) process.argv.push('--dev');
  process.env.NIM_PROXY_TEST_HOME = homeDir;
  return Promise.resolve()
    .then(() => fn(homeDir))
    .finally(() => {
      if (!argvHadDev) {
        const idx = process.argv.indexOf('--dev');
        if (idx !== -1) process.argv.splice(idx, 1);
      }
      if (originalTestHome === undefined) delete process.env.NIM_PROXY_TEST_HOME;
      else process.env.NIM_PROXY_TEST_HOME = originalTestHome;
      fs.rmSync(homeDir, { recursive: true, force: true });
    });
}

function fakeSafeStorage() {
  return {
    isEncryptionAvailable: () => true,
    encryptString: (s) => Buffer.from(`enc:${s}`, 'utf8'),
    decryptString: (b) => {
      const text = b.toString('utf8');
      if (!text.startsWith('enc:')) throw new Error('bad blob');
      return text.slice(4);
    },
  };
}

// Same pattern as engine-context-config-regen.test.js's fakePm2Control — no
// test in this repo touches a real pm2 daemon.
function fakePm2Control() {
  return {
    APP_NAME: 'litellm-nim',
    getStatus: async () => ({ status: 'not-installed' }),
    startOrRestart: async () => ({ ok: true }),
  };
}

/**
 * Lays down exactly what a real pre-CCA-15 install has on disk: a config
 * directory generated by generateAll() and a manifest.json with no
 * `connections`/`activeConnectionId` fields at all, since that shape never
 * existed before this task. Mirrors engine-context-config-regen.test.js's
 * seedStaleInstall (same generateAll call shape), kept as its own local copy
 * rather than a shared import — see that file's own note on why these
 * fixtures are deliberately retyped per test file, not centralized.
 */
function seedPreCCA15Install(homeDir, overrides = {}) {
  const configDir = paths.resolveConfigDir({ homedir: homeDir, ...paths.resolveWindowsAppDataOverrides(homeDir) });
  const files = paths.getFilePaths(configDir);

  generateAll({
    files,
    primaryModelId: 'meta/llama-3.1-8b-instruct',
    smallModelId: 'meta/llama-3.1-8b-instruct',
    nimBaseUrl: undefined,
    port: 4000,
    litellmAbsPath: '/usr/local/bin/litellm',
    nvidiaApiKey: 'nvapi-old-install',
  });

  const manifest = {
    version: 1,
    port: 4000,
    primary_model: 'meta/llama-3.1-8b-instruct',
    small_model: 'meta/llama-3.1-8b-instruct',
    nim_base_url: null,
    litellm_path: '/usr/local/bin/litellm',
    pm2_app: 'litellm-nim',
    cli_configured: false,
    secret_store_backend: 'electron-safeStorage',
    generated_by_version: '0.1.9',
    ...overrides,
  };
  fs.writeFileSync(files.manifestJson, JSON.stringify(manifest, null, 2) + '\n', 'utf8');

  return files;
}

function seedLegacySecretStoreFile(userDataDir, plaintextApiKey) {
  fs.mkdirSync(userDataDir, { recursive: true });
  fs.writeFileSync(path.join(userDataDir, 'nim-key.enc'), `enc:${plaintextApiKey}`, 'utf8');
}

// CCA-15.1 AC#3/#4: a REAL migration test against a genuine pre-CCA-15
// fixture — manifest.json with no `connections` field at all, plus the
// encrypted nim-key.enc a real apiKey.validateAndSave() call would have
// produced (seedLegacySecretStoreFile) — not just an assertion made in
// isolation against the pure migrateManifestToConnections() function.
// generated_by_version is pre-stamped to match createEngineContext()'s own
// appVersion below so NCOW-30's config regeneration doesn't also fire and
// muddy what this test is actually proving.
test('createEngineContext: a real pre-CCA-15 install (no manifest.connections, legacy secretStore file) migrates into one named connection on launch, credential intact, zero manual steps', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedPreCCA15Install(homeDir, { generated_by_version: '0.2.0' });
    const userDataDir = path.join(homeDir, 'userData');
    seedLegacySecretStoreFile(userDataDir, 'nvapi-old-install');

    const manifestBefore = JSON.parse(fs.readFileSync(files.manifestJson, 'utf8'));
    assert.equal(manifestBefore.connections, undefined, 'sanity check: the seeded fixture predates the connections field');

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir,
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control: fakePm2Control(),
    });
    await context.configRegeneration;

    // (1) The on-disk manifest genuinely migrated: a real connections array
    // with the previously-implicit connection's fields, plus activeConnectionId
    // pointing at it.
    const manifestAfter = JSON.parse(fs.readFileSync(files.manifestJson, 'utf8'));
    assert.equal(manifestAfter.connections.length, 1);
    const connection = manifestAfter.connections[0];
    assert.equal(connection.id, manifestAfter.activeConnectionId);
    assert.equal(connection.provider, 'nvidia-nim');
    assert.equal(connection.primary_model, 'meta/llama-3.1-8b-instruct');
    assert.equal(connection.small_model, 'meta/llama-3.1-8b-instruct');

    // Additive, not destructive — every top-level field the rest of the app
    // (config regen, updatePort, catalog.fetch, ...) still reads directly
    // stays exactly where it was.
    assert.equal(manifestAfter.port, 4000);
    assert.equal(manifestAfter.primary_model, 'meta/llama-3.1-8b-instruct');
    assert.equal(manifestAfter.litellm_path, '/usr/local/bin/litellm');

    // (2) The credential moved to the new connection-keyed slot, readable
    // with zero manual re-entry, through the real secretStore.loadFor API —
    // not just present as a copied file.
    const context2 = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir,
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control: fakePm2Control(),
    });
    await context2.configRegeneration;
    // secretStore isn't exposed on the returned context directly, so read the
    // migrated credential back the same way engine-context.js itself would:
    // via a fresh secretStore pointed at the same userData path.
    const { createSecretStore } = require('../../src/engine/secretStore');
    const secretStore = createSecretStore(fakeSafeStorage(), path.join(userDataDir, 'nim-key.enc'));
    assert.equal(secretStore.loadFor(connection.id), 'nvapi-old-install');

    // Legacy single slot is left in place too (never destructive) — see
    // connectionsMigration.js's own additive-not-destructive framing.
    assert.equal(secretStore.load(), 'nvapi-old-install');
  });
});

test('createEngineContext: migration is idempotent — a second launch against an already-migrated manifest does not mint a new connection or duplicate the credential', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedPreCCA15Install(homeDir, { generated_by_version: '0.2.0' });
    const userDataDir = path.join(homeDir, 'userData');
    seedLegacySecretStoreFile(userDataDir, 'nvapi-old-install');

    const deps = () => ({
      safeStorage: fakeSafeStorage(),
      userDataDir,
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control: fakePm2Control(),
    });

    const first = createEngineContext(deps());
    await first.configRegeneration;
    const afterFirst = JSON.parse(fs.readFileSync(files.manifestJson, 'utf8'));
    assert.equal(afterFirst.connections.length, 1);
    const firstConnectionId = afterFirst.connections[0].id;

    const second = createEngineContext(deps());
    await second.configRegeneration;
    const afterSecond = JSON.parse(fs.readFileSync(files.manifestJson, 'utf8'));

    assert.equal(afterSecond.connections.length, 1, 'must not mint a second connection on a second launch');
    assert.equal(afterSecond.connections[0].id, firstConnectionId, 'the connection id must be stable across launches');
    assert.equal(afterSecond.activeConnectionId, firstConnectionId);
  });
});

// Same bug class engine-context-config-regen.test.js's own corrupt-manifest
// regression test guards against (readManifest() does a bare JSON.parse, and
// writeManifest() is a non-atomic writeFileSync, so a crash/power-loss mid-
// write leaves exactly this shape on disk): the connections migration reuses
// manifestForRegenCheck specifically so it inherits that same guard instead
// of taking its own unguarded second read.
test('createEngineContext: a corrupt/truncated manifest.json does not throw out of createEngineContext(), and the migration is skipped rather than crashing', async () => {
  await withFakeHome(async (homeDir) => {
    const configDir = paths.resolveConfigDir({ homedir: homeDir, ...paths.resolveWindowsAppDataOverrides(homeDir) });
    const files = paths.getFilePaths(configDir);
    fs.mkdirSync(configDir, { recursive: true });
    fs.writeFileSync(files.manifestJson, '{ "version": 1, "port": 40', 'utf8');

    assert.doesNotThrow(() => {
      createEngineContext({
        safeStorage: fakeSafeStorage(),
        userDataDir: path.join(homeDir, 'userData'),
        appDataDir: path.join(homeDir, 'appData'),
        broadcast: () => {},
        appVersion: '0.2.0',
        pm2Control: fakePm2Control(),
      });
    });

    // Untouched — a corrupt manifest is left exactly as-is, not overwritten
    // with a half-migrated guess.
    assert.equal(fs.readFileSync(files.manifestJson, 'utf8'), '{ "version": 1, "port": 40');
  });
});

test('createEngineContext: a fresh install (no manifest at all, setup never run) does not crash and creates no connections', async () => {
  await withFakeHome(async (homeDir) => {
    const userDataDir = path.join(homeDir, 'userData');
    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir,
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control: fakePm2Control(),
    });
    await context.configRegeneration;
    const manifestResult = await context.handlers.config.getManifest();
    assert.equal(manifestResult.data, null);
  });
});
