'use strict';

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const { createEngineContext } = require('../../src/main/engine-context');
const { generateAll } = require('../../src/engine/configGen');
const paths = require('../../src/engine/paths');

// Mirrors test/main/engine-context-apikey.test.js's withFakeHome — the only
// sanctioned way (per CLAUDE.md) to point createEngineContext() at a
// throwaway directory instead of this machine's real ~/.config/claude-conduit.
function withFakeHome(fn) {
  const homeDir = fs.mkdtempSync(path.join(os.tmpdir(), 'nim-engine-context-regen-test-'));
  const argvHadDev = process.argv.includes('--dev');
  const originalTestHome = process.env.NIM_PROXY_TEST_HOME;
  if (!argvHadDev) process.argv.push('--dev');
  process.env.NIM_PROXY_TEST_HOME = homeDir;
  return Promise.resolve()
    .then(() => fn(homeDir))
    .finally(() => {
      if (!argvHadDev) {
        const idx = process.argv.indexOf('--dev');
        if (idx !== -1) process.argv.splice(idx, 1);
      }
      if (originalTestHome === undefined) delete process.env.NIM_PROXY_TEST_HOME;
      else process.env.NIM_PROXY_TEST_HOME = originalTestHome;
      fs.rmSync(homeDir, { recursive: true, force: true });
    });
}

function fakeSafeStorage() {
  return {
    isEncryptionAvailable: () => true,
    encryptString: (s) => Buffer.from(`enc:${s}`, 'utf8'),
    decryptString: (b) => b.toString('utf8').slice(4),
  };
}

// NCOW-30: createEngineContext hardcodes require('pm2') for its REAL
// pm2Control (see engine-context.js) — every existing test in this repo
// (engine-context-apikey.test.js, shutdown.test.js's own fakePm2 pattern)
// carefully avoids exercising any pm2-touching code path for exactly that
// reason: connecting to/spawning a real system pm2 daemon during `npm test`
// is not something any test here does. engine-context.js's optional
// deps.pm2Control override (added for this task) lets this test observe the
// NCOW-30 stale-config-regeneration wiring end to end without ever touching
// a real pm2 daemon.
function fakePm2Control({ status = 'not-installed' } = {}) {
  const calls = { getStatus: 0, startOrRestart: [] };
  return {
    calls,
    pm2Control: {
      APP_NAME: 'litellm-nim',
      getStatus: async () => {
        calls.getStatus += 1;
        return { status };
      },
      startOrRestart: async (opts) => {
        calls.startOrRestart.push(opts);
        return { ok: true };
      },
    },
  };
}

/**
 * Lays down exactly what a real pre-NCOW-30 install has on disk: a config
 * directory generated by generateAll() (version-agnostic — this is honestly
 * what an old build's setup wizard produced) plus a manifest.json with no
 * generated_by_version field at all, since that field never existed before
 * this task.
 */
function seedStaleInstall(homeDir) {
  const configDir = paths.resolveConfigDir({ homedir: homeDir });
  const files = paths.getFilePaths(configDir);

  generateAll({
    files,
    primaryModelId: 'meta/llama-3.1-8b-instruct',
    smallModelId: 'meta/llama-3.1-8b-instruct',
    nimBaseUrl: undefined,
    port: 4000,
    litellmAbsPath: '/usr/local/bin/litellm',
    nvidiaApiKey: 'nvapi-old-install',
  });

  const manifest = {
    version: 1,
    port: 4000,
    primary_model: 'meta/llama-3.1-8b-instruct',
    small_model: 'meta/llama-3.1-8b-instruct',
    nim_base_url: null,
    litellm_path: '/usr/local/bin/litellm',
    pm2_app: 'litellm-nim',
    cli_configured: false,
    secret_store_backend: 'electron-safeStorage',
  };
  fs.writeFileSync(files.manifestJson, JSON.stringify(manifest, null, 2) + '\n', 'utf8');

  return files;
}

test('createEngineContext: an upgraded install (stale generated config, older/no version marker) regenerates on launch without re-running setup', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedStaleInstall(homeDir);
    const { pm2Control, calls } = fakePm2Control({ status: 'not-installed' });

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
    });

    const result = await context.configRegeneration;
    assert.deepEqual(result, { regenerated: true });

    const manifestAfter = JSON.parse(fs.readFileSync(files.manifestJson, 'utf8'));
    assert.equal(manifestAfter.generated_by_version, '0.2.0');

    const cjs = fs.readFileSync(files.ecosystemConfig, 'utf8');
    assert.match(cjs, /interpreter:\s*process\.execPath,/);
    assert.match(cjs, /PYTHONIOENCODING/);

    // Not running at launch (the ordinary case — see NCOW-4) — no restart.
    assert.equal(calls.getStatus, 1);
    assert.equal(calls.startOrRestart.length, 0);
  });
});

test('createEngineContext: AC#2 — regenerating while the proxy is already running restarts it the same way proxy.start()/restart() do', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedStaleInstall(homeDir);
    const { pm2Control, calls } = fakePm2Control({ status: 'running' });

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
    });

    const result = await context.configRegeneration;
    assert.deepEqual(result, { regenerated: true });

    assert.equal(calls.startOrRestart.length, 1);
    assert.deepEqual(calls.startOrRestart[0], {
      ecosystemConfigPath: files.ecosystemConfig,
      port: 4000,
      outLog: files.outLog,
      errLog: files.errLog,
    });
  });
});

test('createEngineContext: a fresh install (no manifest yet) never touches pm2, regardless of appVersion', async () => {
  await withFakeHome(async (homeDir) => {
    const { pm2Control, calls } = fakePm2Control();

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
    });

    const result = await context.configRegeneration;
    assert.deepEqual(result, { regenerated: false, reason: 'up-to-date' });
    assert.equal(calls.getStatus, 0);
    assert.equal(calls.startOrRestart.length, 0);
  });
});

test('createEngineContext: an already up-to-date install is a no-op on the next launch', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedStaleInstall(homeDir);
    const manifest = JSON.parse(fs.readFileSync(files.manifestJson, 'utf8'));
    manifest.generated_by_version = '0.2.0';
    fs.writeFileSync(files.manifestJson, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
    const before = fs.readFileSync(files.ecosystemConfig, 'utf8');

    const { pm2Control, calls } = fakePm2Control({ status: 'running' });
    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
    });

    const result = await context.configRegeneration;
    assert.deepEqual(result, { regenerated: false, reason: 'up-to-date' });
    assert.equal(calls.getStatus, 0, 'must never check proxy status when nothing needs regenerating');
    assert.equal(fs.readFileSync(files.ecosystemConfig, 'utf8'), before);
  });
});

test('createEngineContext: omitting appVersion disables the check entirely (existing callers/tests that never pass it are unaffected)', async () => {
  await withFakeHome(async (homeDir) => {
    seedStaleInstall(homeDir);
    const { pm2Control, calls } = fakePm2Control({ status: 'running' });

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      pm2Control,
    });

    const result = await context.configRegeneration;
    assert.deepEqual(result, { regenerated: false, reason: 'up-to-date' });
    assert.equal(calls.getStatus, 0);
  });
});

// Fix-pass regression test (review of this task's first pass): a
// truncated/corrupt manifest.json must never crash createEngineContext()
// itself. readManifest() does a bare JSON.parse, and this file gets
// rewritten by writeManifest() on every regeneration (non-atomic
// writeFileSync) — so a crash/power-loss/disk-full mid-write leaves exactly
// this shape on disk, and every future upgrade is a fresh opportunity to hit
// it. Before the fix, this threw synchronously out of createEngineContext()
// itself (not inside the promise chain), which app.whenReady().then(...) in
// index.js has no .catch() for — an unhandled rejection with zero renderers.
test('createEngineContext: a corrupt/truncated manifest.json does not throw out of createEngineContext(), and is treated as absent', async () => {
  await withFakeHome(async (homeDir) => {
    const configDir = paths.resolveConfigDir({ homedir: homeDir });
    const files = paths.getFilePaths(configDir);
    fs.mkdirSync(configDir, { recursive: true });
    fs.writeFileSync(files.manifestJson, '{ "version": 1, "port": 40', 'utf8');

    const { pm2Control, calls } = fakePm2Control({ status: 'running' });

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
    });

    const result = await context.configRegeneration;
    // needsRegeneration() already treats an absent manifest as nothing to
    // regenerate — a corrupt manifest is deliberately folded into that same
    // safe path rather than treated as a distinct error.
    assert.deepEqual(result, { regenerated: false, reason: 'up-to-date' });
    assert.equal(calls.getStatus, 0);
    assert.equal(calls.startOrRestart.length, 0);
  });
});

test('createEngineContext: a stale manifest with no litellm_path skips regeneration instead of generating with an undefined path', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedStaleInstall(homeDir);
    const manifest = JSON.parse(fs.readFileSync(files.manifestJson, 'utf8'));
    delete manifest.litellm_path;
    fs.writeFileSync(files.manifestJson, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
    const cjsBefore = fs.readFileSync(files.ecosystemConfig, 'utf8');

    const { pm2Control, calls } = fakePm2Control({ status: 'running' });
    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
    });

    const result = await context.configRegeneration;
    assert.deepEqual(result, { regenerated: false, reason: 'no-litellm-path' });
    assert.equal(calls.getStatus, 0, 'must bail before ever checking proxy status');
    assert.equal(calls.startOrRestart.length, 0);
    assert.equal(fs.readFileSync(files.ecosystemConfig, 'utf8'), cjsBefore, 'must not overwrite the generated config with garbage');
  });
});

test('createEngineContext: a failed restart during regeneration resolves to reason:"error" instead of rejecting/crashing startup', async () => {
  await withFakeHome(async (homeDir) => {
    seedStaleInstall(homeDir);
    const calls = { getStatus: 0 };
    const pm2Control = {
      APP_NAME: 'litellm-nim',
      getStatus: async () => {
        calls.getStatus += 1;
        return { status: 'running' };
      },
      startOrRestart: async () => {
        throw new Error('pm2 restart failed: HEALTH_CHECK_TIMEOUT');
      },
    };

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
    });

    // Must resolve, never reject — this is what keeps a failed restart from
    // ever becoming an unhandled rejection at startup.
    const result = await context.configRegeneration;
    assert.equal(result.regenerated, false);
    assert.equal(result.reason, 'error');
    assert.match(result.error.message, /HEALTH_CHECK_TIMEOUT/);
    assert.equal(calls.getStatus, 1);
  });
});

// index.js itself can't be required under plain `node --test` (it touches
// electron.app at module scope) — mirrors auto-update-wiring.test.js's
// static source-check approach for the same reason.
test('index.js: a failed configRegeneration is logged, not silently dropped', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', '..', 'src', 'main', 'index.js'), 'utf8');
  assert.match(source, /const \{ handlers, pm2Control, configRegeneration, mutexes \} = createEngineContext/);
  assert.match(source, /configRegeneration[\s\S]{0,200}console\.warn/, 'expected configRegeneration to be observed and logged on failure');
});
