'use strict';

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const { createEngineContext } = require('../../src/main/engine-context');
const { generateAll } = require('../../src/engine/configGen');
const paths = require('../../src/engine/paths');

// Mirrors test/main/engine-context-apikey.test.js's withFakeHome — the only
// sanctioned way (per CLAUDE.md) to point createEngineContext() at a
// throwaway directory instead of this machine's real ~/.config/claude-conduit.
function withFakeHome(fn) {
  const homeDir = fs.mkdtempSync(path.join(os.tmpdir(), 'nim-engine-context-regen-test-'));
  const argvHadDev = process.argv.includes('--dev');
  const originalTestHome = process.env.NIM_PROXY_TEST_HOME;
  if (!argvHadDev) process.argv.push('--dev');
  process.env.NIM_PROXY_TEST_HOME = homeDir;
  return Promise.resolve()
    .then(() => fn(homeDir))
    .finally(() => {
      if (!argvHadDev) {
        const idx = process.argv.indexOf('--dev');
        if (idx !== -1) process.argv.splice(idx, 1);
      }
      if (originalTestHome === undefined) delete process.env.NIM_PROXY_TEST_HOME;
      else process.env.NIM_PROXY_TEST_HOME = originalTestHome;
      fs.rmSync(homeDir, { recursive: true, force: true });
    });
}

function fakeSafeStorage() {
  return {
    isEncryptionAvailable: () => true,
    encryptString: (s) => Buffer.from(`enc:${s}`, 'utf8'),
    decryptString: (b) => b.toString('utf8').slice(4),
  };
}

// NCOW-30: createEngineContext hardcodes require('pm2') for its REAL
// pm2Control (see engine-context.js) — every existing test in this repo
// (engine-context-apikey.test.js, shutdown.test.js's own fakePm2 pattern)
// carefully avoids exercising any pm2-touching code path for exactly that
// reason: connecting to/spawning a real system pm2 daemon during `npm test`
// is not something any test here does. engine-context.js's optional
// deps.pm2Control override (added for this task) lets this test observe the
// NCOW-30 stale-config-regeneration wiring end to end without ever touching
// a real pm2 daemon.
function fakePm2Control({ status = 'not-installed' } = {}) {
  const calls = { getStatus: 0, startOrRestart: [] };
  return {
    calls,
    pm2Control: {
      APP_NAME: 'litellm-nim',
      getStatus: async () => {
        calls.getStatus += 1;
        return { status };
      },
      startOrRestart: async (opts) => {
        calls.startOrRestart.push(opts);
        return { ok: true };
      },
    },
  };
}

/**
 * NCOW-31: regenerateStaleConfig() now logs its restart outcome, and
 * engine-context.js passes `deps.logger ?? console` through to it. Tests inject
 * a recorder so the distinct success/failure lines can be asserted directly
 * instead of scraped out of process stdout.
 */
function recordingLogger() {
  const warned = [];
  const infoed = [];
  return { warn: (m) => warned.push(m), info: (m) => infoed.push(m), warned, infoed };
}

/**
 * Lays down exactly what a real pre-NCOW-30 install has on disk: a config
 * directory generated by generateAll() (version-agnostic — this is honestly
 * what an old build's setup wizard produced) plus a manifest.json with no
 * generated_by_version field at all, since that field never existed before
 * this task.
 */
function seedStaleInstall(homeDir) {
  const configDir = paths.resolveConfigDir({ homedir: homeDir });
  const files = paths.getFilePaths(configDir);

  generateAll({
    files,
    primaryModelId: 'meta/llama-3.1-8b-instruct',
    smallModelId: 'meta/llama-3.1-8b-instruct',
    nimBaseUrl: undefined,
    port: 4000,
    litellmAbsPath: '/usr/local/bin/litellm',
    nvidiaApiKey: 'nvapi-old-install',
  });

  const manifest = {
    version: 1,
    port: 4000,
    primary_model: 'meta/llama-3.1-8b-instruct',
    small_model: 'meta/llama-3.1-8b-instruct',
    nim_base_url: null,
    litellm_path: '/usr/local/bin/litellm',
    pm2_app: 'litellm-nim',
    cli_configured: false,
    secret_store_backend: 'electron-safeStorage',
  };
  fs.writeFileSync(files.manifestJson, JSON.stringify(manifest, null, 2) + '\n', 'utf8');

  return files;
}

test('createEngineContext: an upgraded install (stale generated config, older/no version marker) regenerates on launch without re-running setup', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedStaleInstall(homeDir);
    const { pm2Control, calls } = fakePm2Control({ status: 'not-installed' });

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger: recordingLogger(),
    });

    const result = await context.configRegeneration;
    assert.deepEqual(result, { regenerated: true, restarted: false });

    const manifestAfter = JSON.parse(fs.readFileSync(files.manifestJson, 'utf8'));
    assert.equal(manifestAfter.generated_by_version, '0.2.0');

    const cjs = fs.readFileSync(files.ecosystemConfig, 'utf8');
    assert.match(cjs, /interpreter:\s*process\.execPath,/);
    assert.match(cjs, /PYTHONIOENCODING/);

    // Not running at launch (the ordinary case — see NCOW-4) — no restart.
    assert.equal(calls.getStatus, 1);
    assert.equal(calls.startOrRestart.length, 0);
  });
});

test('createEngineContext: AC#2 — regenerating while the proxy is already running restarts it the same way proxy.start()/restart() do', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedStaleInstall(homeDir);
    const { pm2Control, calls } = fakePm2Control({ status: 'running' });

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger: recordingLogger(),
    });

    const result = await context.configRegeneration;
    assert.deepEqual(result, { regenerated: true, restarted: true });

    assert.equal(calls.startOrRestart.length, 1);
    assert.deepEqual(calls.startOrRestart[0], {
      ecosystemConfigPath: files.ecosystemConfig,
      port: 4000,
      outLog: files.outLog,
      errLog: files.errLog,
    });
  });
});

test('createEngineContext: a fresh install (no manifest yet) never touches pm2, regardless of appVersion', async () => {
  await withFakeHome(async (homeDir) => {
    const { pm2Control, calls } = fakePm2Control();

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger: recordingLogger(),
    });

    const result = await context.configRegeneration;
    assert.deepEqual(result, { regenerated: false, reason: 'up-to-date' });
    assert.equal(calls.getStatus, 0);
    assert.equal(calls.startOrRestart.length, 0);
  });
});

test('createEngineContext: an already up-to-date install is a no-op on the next launch', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedStaleInstall(homeDir);
    const manifest = JSON.parse(fs.readFileSync(files.manifestJson, 'utf8'));
    manifest.generated_by_version = '0.2.0';
    fs.writeFileSync(files.manifestJson, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
    const before = fs.readFileSync(files.ecosystemConfig, 'utf8');

    const { pm2Control, calls } = fakePm2Control({ status: 'running' });
    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger: recordingLogger(),
    });

    const result = await context.configRegeneration;
    assert.deepEqual(result, { regenerated: false, reason: 'up-to-date' });
    assert.equal(calls.getStatus, 0, 'must never check proxy status when nothing needs regenerating');
    assert.equal(fs.readFileSync(files.ecosystemConfig, 'utf8'), before);
  });
});

test('createEngineContext: omitting appVersion disables the check entirely (existing callers/tests that never pass it are unaffected)', async () => {
  await withFakeHome(async (homeDir) => {
    seedStaleInstall(homeDir);
    const { pm2Control, calls } = fakePm2Control({ status: 'running' });

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      pm2Control,
      logger: recordingLogger(),
    });

    const result = await context.configRegeneration;
    assert.deepEqual(result, { regenerated: false, reason: 'up-to-date' });
    assert.equal(calls.getStatus, 0);
  });
});

// Fix-pass regression test (review of this task's first pass): a
// truncated/corrupt manifest.json must never crash createEngineContext()
// itself. readManifest() does a bare JSON.parse, and this file gets
// rewritten by writeManifest() on every regeneration (non-atomic
// writeFileSync) — so a crash/power-loss/disk-full mid-write leaves exactly
// this shape on disk, and every future upgrade is a fresh opportunity to hit
// it. Before the fix, this threw synchronously out of createEngineContext()
// itself (not inside the promise chain), which app.whenReady().then(...) in
// index.js has no .catch() for — an unhandled rejection with zero renderers.
test('createEngineContext: a corrupt/truncated manifest.json does not throw out of createEngineContext(), and is treated as absent', async () => {
  await withFakeHome(async (homeDir) => {
    const configDir = paths.resolveConfigDir({ homedir: homeDir });
    const files = paths.getFilePaths(configDir);
    fs.mkdirSync(configDir, { recursive: true });
    fs.writeFileSync(files.manifestJson, '{ "version": 1, "port": 40', 'utf8');

    const { pm2Control, calls } = fakePm2Control({ status: 'running' });

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger: recordingLogger(),
    });

    const result = await context.configRegeneration;
    // needsRegeneration() already treats an absent manifest as nothing to
    // regenerate — a corrupt manifest is deliberately folded into that same
    // safe path rather than treated as a distinct error.
    assert.deepEqual(result, { regenerated: false, reason: 'up-to-date' });
    assert.equal(calls.getStatus, 0);
    assert.equal(calls.startOrRestart.length, 0);
  });
});

test('createEngineContext: a stale manifest with no litellm_path skips regeneration instead of generating with an undefined path', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedStaleInstall(homeDir);
    const manifest = JSON.parse(fs.readFileSync(files.manifestJson, 'utf8'));
    delete manifest.litellm_path;
    fs.writeFileSync(files.manifestJson, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
    const cjsBefore = fs.readFileSync(files.ecosystemConfig, 'utf8');

    const { pm2Control, calls } = fakePm2Control({ status: 'running' });
    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger: recordingLogger(),
    });

    const result = await context.configRegeneration;
    assert.deepEqual(result, { regenerated: false, reason: 'no-litellm-path' });
    assert.equal(calls.getStatus, 0, 'must bail before ever checking proxy status');
    assert.equal(calls.startOrRestart.length, 0);
    assert.equal(fs.readFileSync(files.ecosystemConfig, 'utf8'), cjsBefore, 'must not overwrite the generated config with garbage');
  });
});

test('createEngineContext: a THROWN restart during regeneration resolves (never rejects) and reports the restart-error shape', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedStaleInstall(homeDir);
    const calls = { getStatus: 0 };
    const pm2Control = {
      APP_NAME: 'litellm-nim',
      getStatus: async () => {
        calls.getStatus += 1;
        return { status: 'running' };
      },
      startOrRestart: async () => {
        throw new Error('pm2 restart failed: HEALTH_CHECK_TIMEOUT');
      },
    };
    const logger = recordingLogger();

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger,
    });

    // Must resolve, never reject — this is what keeps a failed restart from
    // ever becoming an unhandled rejection at startup.
    const result = await context.configRegeneration;
    assert.equal(result.regenerated, false);
    // NCOW-31: 'restart-error' rather than the old catch-all 'error' — the
    // failure is now recognised and handled where it happens, not swallowed by
    // engine-context.js's outer .catch(). That outer catch remains, for any
    // *other* throw (e.g. generateAll() failing on a read-only disk).
    assert.equal(result.reason, 'restart-error');
    assert.match(result.error.message, /HEALTH_CHECK_TIMEOUT/);
    assert.equal(calls.getStatus, 1);

    // AC#2: unstamped on disk, and logged distinctly from success.
    const manifestAfter = JSON.parse(fs.readFileSync(files.manifestJson, 'utf8'));
    assert.equal(manifestAfter.generated_by_version, undefined);
    assert.deepEqual(logger.infoed, []);
    assert.equal(logger.warned.length, 1);
    assert.match(logger.warned[0], /THREW/);
  });
});

test('createEngineContext: AC#2 — a TIMED-OUT restart ({ok:false, HEALTH_CHECK_TIMEOUT}) leaves generated_by_version unstamped on disk', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedStaleInstall(homeDir);
    const pm2Control = {
      APP_NAME: 'litellm-nim',
      getStatus: async () => ({ status: 'running' }),
      // pm2Control.startOrRestart()'s real timeout return: no throw at all.
      // Before NCOW-31 this shape was never even inspected, so the manifest was
      // stamped and this launch's failure became permanent.
      startOrRestart: async () => ({
        ok: false,
        error: { code: 'HEALTH_CHECK_TIMEOUT', message: 'litellm did not become healthy in time.' },
        outTail: [],
        errTail: [],
      }),
    };
    const logger = recordingLogger();

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger,
    });

    const result = await context.configRegeneration;
    assert.equal(result.regenerated, false);
    assert.equal(result.reason, 'restart-failed');
    assert.equal(result.error.code, 'HEALTH_CHECK_TIMEOUT');

    const manifestAfter = JSON.parse(fs.readFileSync(files.manifestJson, 'utf8'));
    assert.equal(manifestAfter.generated_by_version, undefined, 'a timed-out restart must not stamp the manifest');
    assert.deepEqual(logger.infoed, []);
    assert.equal(logger.warned.length, 1);
    assert.match(logger.warned[0], /FAILED/);
    assert.match(logger.warned[0], /HEALTH_CHECK_TIMEOUT/);
  });
});

test('createEngineContext: AC#3b — the NEXT launch retries a failed regeneration against the real on-disk manifest', async () => {
  await withFakeHome(async (homeDir) => {
    const files = seedStaleInstall(homeDir);

    const deps = () => ({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      logger: recordingLogger(),
    });

    // Launch 1 — restart times out.
    const firstRestarts = [];
    const firstResult = await createEngineContext({
      ...deps(),
      pm2Control: {
        APP_NAME: 'litellm-nim',
        getStatus: async () => ({ status: 'running' }),
        startOrRestart: async (opts) => {
          firstRestarts.push(opts);
          return { ok: false, error: { code: 'HEALTH_CHECK_TIMEOUT', message: 'nope' } };
        },
      },
    }).configRegeneration;
    assert.equal(firstResult.reason, 'restart-failed');
    assert.equal(firstRestarts.length, 1);

    // Launch 2 — brand-new context, reading the SAME manifest.json back off
    // disk. This is the whole point: it must still look stale.
    const secondRestarts = [];
    const secondResult = await createEngineContext({
      ...deps(),
      pm2Control: {
        APP_NAME: 'litellm-nim',
        getStatus: async () => ({ status: 'running' }),
        startOrRestart: async (opts) => {
          secondRestarts.push(opts);
          return { ok: true };
        },
      },
    }).configRegeneration;
    assert.deepEqual(secondResult, { regenerated: true, restarted: true });
    assert.equal(secondRestarts.length, 1, 'the second launch actually retried the restart');
    assert.equal(JSON.parse(fs.readFileSync(files.manifestJson, 'utf8')).generated_by_version, '0.2.0');

    // Launch 3 — now settled, so it must stop retrying.
    const thirdRestarts = [];
    const thirdResult = await createEngineContext({
      ...deps(),
      pm2Control: {
        APP_NAME: 'litellm-nim',
        getStatus: async () => ({ status: 'running' }),
        startOrRestart: async (opts) => {
          thirdRestarts.push(opts);
          return { ok: true };
        },
      },
    }).configRegeneration;
    assert.deepEqual(thirdResult, { regenerated: false, reason: 'up-to-date' });
    assert.equal(thirdRestarts.length, 0);
  });
});

// ---------------------------------------------------------------------------
// NCOW-31 AC#1 — serialization, observed end to end through the real
// createEngineContext wiring (not just configGen's injected runner).
// ---------------------------------------------------------------------------

function deferred() {
  let resolve;
  const promise = new Promise((res) => {
    resolve = res;
  });
  return { promise, resolve };
}

test('createEngineContext: AC#1 — a user-initiated proxy op taking context.mutexes.proxy CANNOT interleave with the background regeneration restart', async () => {
  await withFakeHome(async (homeDir) => {
    seedStaleInstall(homeDir);
    const order = [];
    const restartGate = deferred();

    const pm2Control = {
      APP_NAME: 'litellm-nim',
      getStatus: async () => ({ status: 'running' }),
      startOrRestart: async () => {
        order.push('bg-restart:enter');
        // Stands in for startOrRestart()'s up-to-60s health-check window —
        // exactly the window NCOW-31 exists to cover.
        await restartGate.promise;
        order.push('bg-restart:exit');
        return { ok: true };
      },
      stop: async () => {
        order.push('user-stop:pm2.stop');
      },
    };

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger: recordingLogger(),
    });

    // Exactly how ipc.js invokes a mutating proxy handler: the real handler,
    // decorated with the real shared lock off the real context.
    const userStop = context.mutexes.proxy(async () => {
      order.push('user-stop:enter');
      return context.handlers.proxy.stop();
    })();

    // Wait for the restart to be genuinely in flight (a condition, not a fixed
    // number of microtask turns — the latter would make this test's *setup*
    // timing-sensitive), then let everything else that CAN progress, progress.
    while (!order.includes('bg-restart:enter')) await new Promise((r) => setImmediate(r));
    for (let i = 0; i < 20; i++) await Promise.resolve();

    assert.deepEqual(
      order,
      ['bg-restart:enter'],
      'the user Stop must be queued behind the in-flight background restart, not interleaved with it'
    );

    restartGate.resolve();
    const regen = await context.configRegeneration;
    await userStop;

    assert.deepEqual(regen, { regenerated: true, restarted: true });
    assert.deepEqual(order, [
      'bg-restart:enter',
      'bg-restart:exit',
      'user-stop:enter',
      'user-stop:pm2.stop',
    ]);
  });
});

test('createEngineContext: NCOW-31 fix pass 2 (reviewer finding B1) — the tray path (mutexes.proxy.run(...) wrapping handlers.proxy.*, the same shape tray.js\'s createTrayActions now wires into main/index.js\'s createTray({...})) also cannot interleave with the background regeneration restart', async () => {
  await withFakeHome(async (homeDir) => {
    seedStaleInstall(homeDir);
    const order = [];
    const restartGate = deferred();

    const pm2Control = {
      APP_NAME: 'litellm-nim',
      getStatus: async () => ({ status: 'running' }),
      startOrRestart: async () => {
        order.push('bg-restart:enter');
        // Stands in for startOrRestart()'s up-to-60s health-check window —
        // exactly the window NCOW-31 exists to cover.
        await restartGate.promise;
        order.push('bg-restart:exit');
        return { ok: true };
      },
      stop: async () => {
        order.push('tray-stop:pm2.stop');
      },
    };

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger: recordingLogger(),
    });

    // Before fix pass 2, main/index.js's createTray({ onStop }) called
    // handlers.proxy.stop() directly — no ipcMain, therefore no lock (see the
    // review's finding B1: tray.js only enables Stop/Restart when
    // status.status === 'running', which is exactly this restart's own
    // precondition). It now wraps every tray callback in
    // `mutexes.proxy.run(() => handlers.proxy.X())` via tray.js's exported
    // createTrayActions({ mutexes, handlers }) (NCOW-35) — the same primitive
    // registerIpcHandlers() decorates the IPC handlers with and
    // regenerateStaleConfig()'s own restart takes via `runProxyOperation`.
    // This reproduces that exact call shape off the real context (this file
    // cannot import tray.js itself: it requires('electron') at module scope,
    // which would poison the "pulls no electron into the module graph" test
    // further down in this same file/process). The behavioural proof against
    // the REAL createTrayActions — including identity with a real
    // ipc.js-registered handler and a negative control for the
    // nested-scope-shadowing mutation class review pass 2 identified — lives
    // in test/main/tray-actions.test.js, which is free to require tray.js
    // because it is its own file/process.
    const trayStop = context.mutexes.proxy.run(() => {
      order.push('tray-stop:enter');
      return context.handlers.proxy.stop();
    });

    // Wait for the restart to be genuinely in flight (a condition, not a fixed
    // number of microtask turns — the latter would make this test's *setup*
    // timing-sensitive), then let everything else that CAN progress, progress.
    while (!order.includes('bg-restart:enter')) await new Promise((r) => setImmediate(r));
    for (let i = 0; i < 20; i++) await Promise.resolve();

    assert.deepEqual(
      order,
      ['bg-restart:enter'],
      'the tray Stop must be queued behind the in-flight background restart, not interleaved with it'
    );

    restartGate.resolve();
    const regen = await context.configRegeneration;
    await trayStop;

    assert.deepEqual(regen, { regenerated: true, restarted: true });
    assert.deepEqual(order, [
      'bg-restart:enter',
      'bg-restart:exit',
      'tray-stop:enter',
      'tray-stop:pm2.stop',
    ]);
  });
});

test('createEngineContext: negative control — calling the handler with NO lock at all still interleaves, proving the assertion technique above would have caught a real race (not a false negative)', async () => {
  await withFakeHome(async (homeDir) => {
    seedStaleInstall(homeDir);
    const order = [];
    const restartGate = deferred();

    const pm2Control = {
      APP_NAME: 'litellm-nim',
      getStatus: async () => ({ status: 'running' }),
      startOrRestart: async () => {
        order.push('bg-restart:enter');
        await restartGate.promise;
        order.push('bg-restart:exit');
        return { ok: true };
      },
      stop: async () => {
        order.push('unlocked-stop:pm2.stop');
      },
    };

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      pm2Control,
      logger: recordingLogger(),
    });

    // Wait until the background restart is genuinely in flight, so "in the
    // middle" means exactly that.
    while (!order.includes('bg-restart:enter')) await new Promise((r) => setImmediate(r));

    // Deliberately bypasses BOTH locked call paths this task closes (ipc.js's
    // IPC-mediated handler above, and now main/index.js's tray wiring in the
    // test above) by invoking the raw handler with no lock in between at all.
    // This is not a description of any real call path left in the app after
    // fix pass 2 — every real caller now goes through one of the two locked
    // tests above. It exists purely so this suite proves its own
    // interleave-detection technique (wait for bg-restart:enter, then assert
    // `order`) actually catches a genuine race, ruling out the two tests above
    // passing merely because nothing in this test setup could ever interleave
    // regardless of locking.
    await context.handlers.proxy.stop();

    assert.deepEqual(
      order,
      ['bg-restart:enter', 'unlocked-stop:pm2.stop'],
      'called with no lock, the Stop lands in the middle of the restart — proving this test methodology would have caught the race the two locked tests above close'
    );
    assert.equal(order.includes('bg-restart:exit'), false, 'the restart really was still running when the Stop landed');

    restartGate.resolve();
    await context.configRegeneration;
  });
});

test('createEngineContext: the returned mutexes are the ones the regeneration restart actually takes (an injected set is honoured)', async () => {
  await withFakeHome(async (homeDir) => {
    seedStaleInstall(homeDir);
    const { createDomainMutexes } = require('../../src/main/mutex');
    const mutexes = createDomainMutexes();
    const order = [];
    const heldGate = deferred();

    // Hold the proxy lock BEFORE createEngineContext even runs. If its
    // regeneration restart takes this same lock, the restart cannot start until
    // this releases.
    const preHeld = mutexes.proxy.run(async () => {
      order.push('pre-held:enter');
      await heldGate.promise;
      order.push('pre-held:exit');
    });

    const context = createEngineContext({
      safeStorage: fakeSafeStorage(),
      userDataDir: path.join(homeDir, 'userData'),
      appDataDir: path.join(homeDir, 'appData'),
      broadcast: () => {},
      appVersion: '0.2.0',
      mutexes,
      pm2Control: {
        APP_NAME: 'litellm-nim',
        getStatus: async () => {
          order.push('bg:getStatus');
          return { status: 'running' };
        },
        startOrRestart: async () => {
          order.push('bg:startOrRestart');
          return { ok: true };
        },
      },
      logger: recordingLogger(),
    });

    assert.equal(context.mutexes, mutexes, 'the context must expose the very same set it uses');

    for (let i = 0; i < 20; i++) await Promise.resolve();
    assert.deepEqual(order, ['pre-held:enter'], 'the background restart must be blocked by the pre-held lock');
    assert.equal(order.includes('bg:getStatus'), false, 'not even the status read may happen inside someone else\'s critical section');

    heldGate.resolve();
    await preHeld;
    await context.configRegeneration;
    assert.deepEqual(order, ['pre-held:enter', 'pre-held:exit', 'bg:getStatus', 'bg:startOrRestart']);
  });
});

// NCOW-31: the constraint that forced the mutex primitive into its own module
// in the first place (see src/main/mutex.js's header). engine-context.js is
// required at the top of THIS file, and every other suite that touches it,
// under plain `node --test` with no Electron runtime — so nothing it pulls in
// transitively may require('electron') at module scope. mutex.js is the new
// edge in that graph; if it ever grows an electron import, roughly a third of
// this repo's suites break at require time and this test says why.
test('engine-context.js: requiring it (and therefore mutex.js) pulls no electron into the module graph', () => {
  assert.ok(require('../../src/main/engine-context').createEngineContext);
  assert.ok(require('../../src/main/mutex').createDomainMutexes);
  const electronEntries = Object.keys(require.cache).filter((k) => /[/\\]node_modules[/\\]electron[/\\]/.test(k));
  assert.deepEqual(electronEntries, []);
});

// index.js itself can't be required under plain `node --test` (it touches
// electron.app at module scope) — mirrors auto-update-wiring.test.js's
// static source-check approach for the same reason.
test('index.js: a failed configRegeneration is logged, not silently dropped', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', '..', 'src', 'main', 'index.js'), 'utf8');
  assert.match(source, /const \{ handlers, pm2Control, configRegeneration, mutexes \} = createEngineContext/);
  assert.match(source, /configRegeneration[\s\S]{0,200}console\.warn/, 'expected configRegeneration to be observed and logged on failure');
});

// NCOW-31 fix pass 2 (reviewer finding B1) / NCOW-35: the tray's
// Start/Stop/Restart used to call handlers.proxy.* directly, bypassing
// ipcMain and therefore the mutex entirely. The original fix inlined
// `onStart: () => mutexes.proxy.run(() => handlers.proxy.start())` etc.
// straight into index.js's createTray({...}) call, provable only by a
// source-text regex over index.js — review pass 2 found that regex has a real
// identity gap: it only checks that the text `mutexes.proxy.run(...)` appears
// at the call site, not that `mutexes` resolves to the SAME lock instance
// ipc.js and engine-context.js use, so a mutation shadowing `mutexes` in a
// nested scope right around this call (giving the tray its own private,
// unshared lock) still passed every test that regex could offer.
//
// NCOW-35 pulls that wiring into tray.js's exported createTrayActions({
// mutexes, handlers }) instead (mirroring menu.js's buildMenuTemplate). The
// identity proof — that the tray, ipc.js, and engine-context.js all contend
// for one shared mutex instance, and that a shadowed/private set is
// detectably different — is now a BEHAVIOURAL test against the real seam, in
// test/main/tray-actions.test.js.
//
// NCOW-35 fix pass (mandatory review): that behavioural test, and the
// call-site regex below, each reach only part of the chain. The behavioural
// test proves createTrayActions({ mutexes, handlers }) shares a lock with
// ipc.js/engine-context.js whenever it is invoked with the SAME `mutexes`
// binding — but it imports tray.js directly and cannot see what identifier
// index.js itself passes in. The call-site regex below only confirms the
// text `...createTrayActions({ mutexes, handlers })` appears inside the
// createTray({...}) call; it is blind to whether `mutexes` resolves to the
// shared instance or a private one, exactly as review pass 2's original
// `mutexes.proxy.run(...)` regex was. A nested block scope wrapped around
// createTray({...}) that shadows `mutexes` with its own
// `require('./mutex').createDomainMutexes()` right before spreading it in
// passes both checks and still leaves the tray fully unlocked — this was
// reproduced against a real reviewer pass and confirmed to slip through
// npm test unnoticed.
//
// index.js itself can't be required under plain `node --test` (electron.app
// at module scope), so this file closes the gap with a second, file-wide
// static check just below: that the `mutexes` identifier is bound exactly
// once anywhere in index.js — the createEngineContext() destructure at the
// top of whenReady() — with no other declaration and no bare reassignment.
// "Is this identifier rebound or re-declared anywhere in this file" is a
// source property a static check can legitimately settle, unlike "does this
// lock actually serialize" (which only the behavioural test can reach).
// Neither check proves full identity alone; together — the behavioural test
// for what it CAN reach, the single-binding check for what it CAN'T — they
// close the chain honestly.
test('index.js: createTray({...}) is wired with tray.js\'s createTrayActions({ mutexes, handlers }), using the context\'s own mutexes/handlers', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', '..', 'src', 'main', 'index.js'), 'utf8');
  assert.match(
    source,
    /const \{ createTray, createTrayActions \} = require\(['"]\.\/tray['"]\)/,
    'expected index.js to import createTrayActions alongside createTray from tray.js'
  );

  const trayCallAt = source.indexOf('createTray({');
  assert.ok(trayCallAt > -1, 'expected to find the createTray({...}) call');
  const trayCallEnd = source.indexOf('});', trayCallAt);
  assert.ok(trayCallEnd > -1, 'expected the createTray({...}) call to close with });');
  const trayBlock = source.slice(trayCallAt, trayCallEnd);

  assert.match(
    trayBlock,
    /\.\.\.createTrayActions\(\{\s*mutexes,\s*handlers\s*\}\)/,
    'createTray({...}) must spread createTrayActions({ mutexes, handlers }) in, using those exact bindings'
  );
});

// NCOW-35 fix pass (mandatory review, finding F1): the check above is a
// call-site regex — it cannot tell a genuinely shared `mutexes` from one
// shadowed by a nested block scope wrapped around the whole createTray({...})
// call, e.g.:
//
//   let tray;
//   {
//     const mutexes = require('./mutex').createDomainMutexes();
//     tray = createTray({ ...createTrayActions({ mutexes, handlers }) });
//   }
//
// That reproduces the exact mutation class review pass 2 identified for the
// old inline `mutexes.proxy.run(...)` wiring — the identity gap didn't close
// when that wiring moved into createTrayActions(), it just moved with it —
// and it passed the call-site regex (and the full suite) before this test
// existed. Checking "is `mutexes` rebound or re-declared anywhere in this
// file" is something a static check CAN legitimately settle (unlike lock
// behaviour), so this asserts index.js binds the identifier exactly once —
// the createEngineContext() destructure — with no shadowing re-declaration
// and no bare reassignment anywhere else in the file.
test('index.js: the `mutexes` identifier is bound exactly once (the createEngineContext() destructure), with no shadowing re-declaration or bare reassignment anywhere else in the file', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', '..', 'src', 'main', 'index.js'), 'utf8');

  // Every place `mutexes` is *bound* to a value via a declaration keyword:
  // the bare form (`const mutexes = ...`) or the destructured form
  // (`const { ..., mutexes, ... } = ...`).
  const declarationPattern = /\b(?:const|let|var)\s+(?:\{[^{}]*\bmutexes\b[^{}]*\}|mutexes\b)\s*=/g;
  const declarations = source.match(declarationPattern) ?? [];
  assert.equal(
    declarations.length,
    1,
    `expected exactly one declaration binding "mutexes" in index.js (the createEngineContext() destructure), found ${declarations.length}: ${JSON.stringify(declarations)}`
  );
  assert.match(
    declarations[0],
    /const \{ handlers, pm2Control, configRegeneration, mutexes \}\s*=$/,
    'the sole "mutexes" binding must be the createEngineContext() destructure, not some other declaration'
  );

  // A bare reassignment (`mutexes = ...`, no declaration keyword) rebinds the
  // identifier just as effectively as a shadowing re-declaration, and is
  // equally invisible to a regex scoped to the createTray({...}) call site.
  const bareAssignmentPattern = /(?<!(?:const|let|var)\s+)\bmutexes\s*=(?!=)/g;
  const bareAssignments = source.match(bareAssignmentPattern) ?? [];
  assert.equal(
    bareAssignments.length,
    0,
    `expected no bare "mutexes = ..." reassignment anywhere in index.js, found: ${JSON.stringify(bareAssignments)}`
  );
});
