'use strict';

const fs = require('node:fs');
const crypto = require('node:crypto');
const { securePrivateFile } = require('./platform');

/**
 * DESIGN.md section 6.1, byte-faithful. Hand-written YAML text rather than a
 * YAML library — the structure is small and fixed, and DESIGN.md's own
 * zero-dependency ethos (its CLI has zero npm deps) is worth preserving here
 * where it costs nothing.
 *
 * @param {{primaryModelId: string, smallModelId: string, nimBaseUrl?: string}} opts
 */
function renderConfigYaml(opts) {
  const apiBaseLine = opts.nimBaseUrl ? `\n      api_base: ${opts.nimBaseUrl}` : '';

  return `model_list:
  # Stable, client-facing IDs shaped like real Anthropic model names (clients
  # validate/expect this format) — re-running setup to swap the underlying
  # NIM model never requires touching client config.
  - model_name: claude-sonnet-4-5    # primary — what Desktop's default + ANTHROPIC_MODEL point at
    litellm_params:
      model: nvidia_nim/${opts.primaryModelId}
      api_key: os.environ/NVIDIA_NIM_API_KEY${apiBaseLine}

  - model_name: claude-haiku-4-5     # background/haiku-class traffic
    litellm_params:
      model: nvidia_nim/${opts.smallModelId}
      api_key: os.environ/NVIDIA_NIM_API_KEY

  # Safety net: Claude clients sometimes request concrete Anthropic IDs
  # (claude-sonnet-4-6, claude-haiku-…, claude-opus-…) regardless of overrides.
  # Route them to the primary model so they don't 400.
  - model_name: "claude-*"
    litellm_params:
      model: nvidia_nim/${opts.primaryModelId}
      api_key: os.environ/NVIDIA_NIM_API_KEY

litellm_settings:
  drop_params: true        # drop Anthropic-only params NIM rejects (cache_control, thinking, metadata…)
  num_retries: 2
  request_timeout: 600

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
`;
}

/**
 * Replaces DESIGN.md section 6.2's bash run.sh with a single Node launcher
 * used on all three platforms — pm2 auto-detects the .js extension and runs
 * it under node, so ecosystem.config.cjs needs no `interpreter` field either.
 * Windows has no bash by default, and a parallel .cmd twin would carry real
 * metacharacter-injection risk if a secret value ever contained %/^/&.
 *
 * Secrets enter ONLY via the sourced litellm.env file, exactly as in
 * DESIGN.md — never via pm2's own `env` field (pm2 persists its process
 * list, env included, to dump.pm2 under PM2_HOME and re-serves it via
 * `pm2 jlist`/`describe`, which would violate the "no secret in any pm2
 * file" property DESIGN.md section 13 AC7 requires).
 *
 * Windows caveat, not fixable here: there are no real POSIX signals, so
 * `child.kill('SIGTERM')` degrades to a hard TerminateProcess — litellm may
 * drop in-flight requests abruptly on `pm2 stop`/`restart` there.
 *
 * @param {{litellmEnvPath: string, litellmAbsPath: string, configYamlPath: string, port: number}} opts
 */
function renderRunLauncherJs(opts) {
  return `'use strict';
// Generated by NIM Proxy Manager — do not edit by hand; re-run setup instead.
const { spawn } = require('node:child_process');
const fs = require('node:fs');

function loadEnvFile(path) {
  const out = {};
  for (const line of fs.readFileSync(path, 'utf8').split('\\n')) {
    const match = /^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/.exec(line.trim());
    if (match) out[match[1]] = match[2];
  }
  return out;
}

const env = { ...process.env, ...loadEnvFile(${JSON.stringify(opts.litellmEnvPath)}) };

const child = spawn(
  ${JSON.stringify(opts.litellmAbsPath)},
  ['--config', ${JSON.stringify(opts.configYamlPath)}, '--host', '127.0.0.1', '--port', ${JSON.stringify(String(opts.port))}],
  { env, stdio: 'inherit' }
);

for (const sig of ['SIGTERM', 'SIGINT', 'SIGHUP']) {
  process.on(sig, () => child.kill(sig));
}
child.on('exit', (code, signal) => process.exit(code ?? (signal ? 1 : 0)));
`;
}

/**
 * DESIGN.md section 7.1, minus the `interpreter` field (pm2 auto-detects
 * .js -> node) and with absolute paths embedded via JSON.stringify — a raw
 * Windows path like C:\\Users\\Jeremy Newhouse\\... contains sequences
 * (\\U, \\N) that aren't valid JS string escapes and would corrupt or throw
 * when this generated file is require()'d; JSON.stringify escapes correctly
 * and transparently handles spaces/non-ASCII usernames too.
 *
 * @param {{runLauncherPath: string, outLog: string, errLog: string}} opts
 */
function renderEcosystemConfigCjs(opts) {
  return `module.exports = {
  apps: [{
    name: 'litellm-nim',
    script: ${JSON.stringify(opts.runLauncherPath)},
    autorestart: true,
    max_restarts: 10,
    restart_delay: 3000,
    kill_timeout: 10000,
    out_file: ${JSON.stringify(opts.outLog)},
    error_file: ${JSON.stringify(opts.errLog)},
    time: true,
  }],
};
`;
}

/**
 * DESIGN.md section 4 Step 4: reuse the existing master key on re-run
 * (idempotent re-setup doesn't invalidate already-configured clients).
 *
 * @param {string} litellmEnvPath
 */
function resolveMasterKey(litellmEnvPath) {
  try {
    const raw = fs.readFileSync(litellmEnvPath, 'utf8');
    const match = /^LITELLM_MASTER_KEY=(.*)$/m.exec(raw);
    if (match && match[1].trim()) return match[1].trim();
  } catch {
    // No existing file (or unreadable) — fall through to generating a new one.
  }
  return 'sk-litellm-' + crypto.randomBytes(24).toString('hex');
}

/**
 * @param {string} litellmEnvPath
 * @param {{nvidiaApiKey: string, masterKey: string}} secrets
 */
function writeSecretsEnvFile(litellmEnvPath, secrets) {
  const content = `NVIDIA_NIM_API_KEY=${secrets.nvidiaApiKey}\nLITELLM_MASTER_KEY=${secrets.masterKey}\n`;
  fs.writeFileSync(litellmEnvPath, content, 'utf8');
  securePrivateFile(litellmEnvPath);
}

/**
 * Orchestrates the full DESIGN.md section 4 Step 4 config generation.
 * Idempotent: re-running against an existing config dir reuses the master
 * key and regenerates every file wholesale (DESIGN.md section 12.1's own
 * re-run-after-partial-failure rule).
 *
 * @param {object} opts
 * @param {import('./paths').getFilePaths extends (...a: any) => infer R ? R : never} opts.files
 * @param {string} opts.primaryModelId
 * @param {string} opts.smallModelId
 * @param {string} opts.nimBaseUrl
 * @param {number} opts.port
 * @param {string} opts.litellmAbsPath
 * @param {string} opts.nvidiaApiKey
 */
function generateAll(opts) {
  const { files } = opts;
  fs.mkdirSync(files.configDir, { recursive: true, mode: 0o700 });
  fs.mkdirSync(files.logsDir, { recursive: true });

  const masterKey = resolveMasterKey(files.litellmEnv);

  fs.writeFileSync(
    files.configYaml,
    renderConfigYaml({ primaryModelId: opts.primaryModelId, smallModelId: opts.smallModelId, nimBaseUrl: opts.nimBaseUrl }),
    'utf8'
  );
  fs.chmodSync(files.configYaml, 0o644);

  writeSecretsEnvFile(files.litellmEnv, { nvidiaApiKey: opts.nvidiaApiKey, masterKey });

  fs.writeFileSync(
    files.runLauncher,
    renderRunLauncherJs({
      litellmEnvPath: files.litellmEnv,
      litellmAbsPath: opts.litellmAbsPath,
      configYamlPath: files.configYaml,
      port: opts.port,
    }),
    'utf8'
  );

  fs.writeFileSync(
    files.ecosystemConfig,
    renderEcosystemConfigCjs({ runLauncherPath: files.runLauncher, outLog: files.outLog, errLog: files.errLog }),
    'utf8'
  );

  // Clean up the orphaned bash launcher when migrating a directory a prior
  // CLI-wizard install created.
  try {
    fs.unlinkSync(files.legacyRunSh);
  } catch {
    // Nothing to clean up — normal on a fresh install.
  }

  return { masterKey };
}

module.exports = {
  renderConfigYaml,
  renderRunLauncherJs,
  renderEcosystemConfigCjs,
  resolveMasterKey,
  writeSecretsEnvFile,
  generateAll,
};
