'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { ipcMain, app, shell } = require('electron');
const { CHANNELS } = require('./ipc-channels');
const { createDomainMutexes, MUTEX_DOMAINS } = require('./mutex');

// Generated by `npm run licenses` and committed. Read through the main process
// rather than imported by the renderer: it's ~190KB of license text that has no
// business in the module graph, and the renderer's CSP sets connect-src 'none',
// so it could not fetch() the file anyway.
const LICENSES_PATH = path.join(__dirname, '..', 'assets', 'licenses.json');

function notImplemented(domain, method) {
  return async () => ({
    ok: false,
    error: { code: 'NOT_IMPLEMENTED', message: `${domain}.${method} is not implemented yet` },
  });
}

/**
 * NCOW-31: the few methods of a mutexed domain that deliberately opt OUT of
 * that domain's lock. Everything else stays locked, which is what this file did
 * for every method of all four mutexed domains before now.
 *
 * Expressed as an opt-out (not an opt-in list of locked methods) on purpose: a
 * method added to a mutexed domain later is then serialized by default, and
 * only becomes unlocked if someone deliberately names it here. The inverse
 * would silently ship new mutating handlers with no lock at all.
 *
 * Why the proxy domain needs any exemption: its lock is now also taken by
 * engine-context.js's launch-time stale-config regeneration, whose restart can
 * legitimately hold it for up to pm2Control.startOrRestart()'s 60s health-check
 * window. The renderer's boot sequence awaits proxy.getStatus() before it
 * renders anything at all (renderer/app.js) and the status pill/poller keeps
 * asking, so locking that would turn exactly the upgrade launch this
 * regeneration exists for into a blank window for up to a minute. getStatus and
 * getRecentLogs are also the only two proxy methods that are pure reads —
 * getStatus lists pm2 apps, getRecentLogs tails two log files off disk. Neither
 * touches the pm2-supervised process or any main-process state, so running one
 * mid-restart cannot corrupt anything; the worst case is a status snapshot that
 * is already stale by the time it is rendered, which is true of every poll tick
 * regardless. testConnection and start/stopLogTail stay locked: the first was
 * locked before this change and would otherwise start failing spuriously
 * against a proxy that is mid-restart, and the log-tail pair mutate
 * engine-context.js's single `logTailUnsubscribe` slot, where two interleaved
 * callers leak a subscription.
 */
const UNSERIALIZED_METHODS = {
  proxy: ['getStatus', 'getRecentLogs'],
  // NCOW-32: update:check reaches neither pm2Control nor the config
  // directory (see autoUpdate.js's performCheck — it only ever talks to
  // GitHub's Releases API on macOS, or electron-updater's own metadata
  // fetch on Windows/Linux) and is fired automatically at every app startup,
  // racing exactly the launch-time background restart that can hold the
  // proxy lock for up to 60s. update:install is the one method of this
  // domain that actually reaches into shared proxy state
  // (installUpdateAndRestart -> stopProxyForShutdown) and stays locked (see
  // DOMAIN_MUTEX_ALIASES below); queuing this pure status read behind a
  // restart would delay every update-status broadcast for no corresponding
  // safety benefit, mirroring proxy's own getStatus/getRecentLogs exemption.
  update: ['check'],
  // NCOW-47: apiKey.getMasked only calls secretStore.load() and masks the
  // result for display (engine-context.js) — it persists nothing and cannot
  // race validateAndSave/clear in any way that corrupts state; the worst
  // case is a masked value that is already stale by the time it renders,
  // same as proxy's getStatus/getRecentLogs and update's check above.
  // clear is NOT listed here — it deletes the encrypted key and stays locked
  // via DOMAIN_MUTEX_ALIASES below, for its whole (fast, synchronous) body.
  //
  // NCOW-50: validateAndSave IS listed here now too, despite persisting the
  // key on success — for a different reason than the pure reads above.
  // Wave-8's integration review of NCOW-47 measured that this method awaits
  // nvidiaKey.validateApiKey() (up to two sequential 10s network round trips
  // against NVIDIA, engine-context.js) BEFORE it ever touches secretStore —
  // and NCOW-47 had this whole handler, including that network wait, locked
  // behind this alias. Composed with NCOW-45's uninstall alias (which
  // reserves claudeCode+config+proxy synchronously and holds all three until
  // it settles — the right call for multi-lock fairness), a slow/offline
  // NVIDIA endpoint turned one Validate-Key click into a ~20s hold on ALL
  // THREE of those locks the moment a user issued an Uninstall afterward —
  // freezing window AND tray Start/Stop/Restart, proxy:testConnection, every
  // claudeCode:* method, and Uninstall's own confirm, with no feedback. See
  // this task's own description for the full reproduction and measured
  // timings.
  //
  // The fix is not "stop locking validateAndSave" — NCOW-47's guarantee (a
  // write here must never interleave with config.generate's
  // secretStore.load()) still has to hold. It is "stop locking it HERE":
  // validateAndSave now acquires mutexes.config itself, directly, inside
  // engine-context.js — but only around the actual secretStore.save() call,
  // after validateApiKey() has already settled. That is a synchronous,
  // milliseconds-long critical section (secretStore.save() calls
  // safeStorage.encryptString — a platform keychain/DPAPI/libsecret round
  // trip — plus a synchronous fs write, so "instant" is optimistic, but it
  // is nowhere near the up-to-two sequential 10s network round trips ahead
  // of it), matching the standard every other entry in this table already
  // applies; the network wait ahead of it now holds no lock at all. See
  // engine-context.js's apiKey.validateAndSave for the actual critical
  // section, and configGen.regenerateStaleConfig's injected
  // runProxyOperation (engine-context.js) for the established precedent of
  // an engine-side critical section acquired against this same shared
  // `mutexes` object rather than through this file's automatic per-method
  // wrapping.
  //
  // This is why validateAndSave is opted out HERE rather than removed from
  // DOMAIN_MUTEX_ALIASES's `apiKey: 'config'` entry below: that alias is
  // still exactly right for `clear`, which has no network component and is
  // correctly locked for its whole (trivial) body.
  //
  // NCOW-49: keeping `validateAndSave` in this array is load-bearing for
  // CORRECTNESS, not just lock scope — see SELF_ACQUIRING_HANDLERS and
  // assertUnserializedMethodsCoverSelfAcquirers() further down this file for
  // the real structural guard against removing it from here without also
  // removing its self-acquisition in engine-context.js. In short:
  // createDomainMutex() (mutex.js) is non-reentrant — chaining `chain =
  // run.catch(() => {})` assumes each acquisition is a fresh call into the
  // chain, not a call already running inside a held lock — so stacking this
  // file's automatic locking back on top of engine-context.js's inner
  // mutexes.config.run() would deadlock `mutexes.config` permanently,
  // wedging every other caller of it too (including uninstall's
  // claudeCode+config+proxy via DOMAIN_MUTEX_ALIASES), not just for the ~20s
  // this fix was scoped to bound. That regression now fails loudly at
  // module load instead of silently reintroducing the deadlock.
  apiKey: ['getMasked', 'validateAndSave'],
  // NCOW-50 AC#5: config.getManifest is an equally pure read of the same
  // manifest.json config.generate writes — manifestStore.readManifest()
  // (engine-context.js's getManifest()) is a bare fs.readFileSync +
  // JSON.parse, no different in kind from apiKey.getMasked's
  // secretStore.load()+mask above, or proxy's getStatus/getRecentLogs.
  // NCOW-47 exempted apiKey.getMasked on exactly this standard but left
  // config.getManifest locked — an inconsistency with no live impact before
  // now (config's own critical sections were already short; see
  // mutex.js's exactly-one-caller argument for why nothing ever raced it in
  // practice) but one that would have quietly gotten worse the moment ANY
  // sufficiently long config-lock holder existed — which validateAndSave's
  // pre-fix network wait briefly was. Applying the same exemption standard
  // here removes the inconsistency outright. `generate` remains the one
  // config method with a genuine mutating concern, and stays locked.
  config: ['getManifest'],
};

/**
 * NCOW-49 AC#8: an explicit, hand-maintained registry of every engine-side
 * handler that self-acquires one of the shared domain mutexes DIRECTLY
 * (rather than being wrapped by this file's automatic per-method locking),
 * paired with which mutex it self-acquires. Today this is exactly one entry:
 * engine-context.js's apiKey.validateAndSave, which runs
 * `mutexes.config.run(() => secretStore.save(key))` itself, after opting out
 * of ipc.js's own locking via UNSERIALIZED_METHODS above (see that entry's
 * own long comment for the full "why").
 *
 * Why this needs its own guard: createDomainMutex()'s FIFO chain (mutex.js)
 * is non-reentrant — `chain = run.catch(() => {})` assumes every acquisition
 * is a fresh call into the chain, never a call already running inside a lock
 * it also holds. If a future edit ever removed `validateAndSave` from
 * UNSERIALIZED_METHODS.apiKey WITHOUT also removing its self-acquisition in
 * engine-context.js, this file would go back to wrapping the whole handler
 * in `mutexes.config` at the IPC layer, on top of the self-acquisition still
 * inside it — the outer acquisition's chain could only resolve after the
 * inner one it's blocking, so neither ever does. That is a PERMANENT
 * deadlock, not a slow path: `mutexes.config` becomes unacquirable for every
 * other caller of it too (including uninstall's claudeCode+config+proxy via
 * DOMAIN_MUTEX_ALIASES below), not just for the ~20s NCOW-50 was scoped to
 * fix.
 *
 * assertUnserializedMethodsCoverSelfAcquirers() below turns that regression
 * from "silently reintroduce a permanent, wedge-everything deadlock" into a
 * loud module-load crash — the same trade this file already makes for
 * LOCK_ACQUISITION_ORDER via assertLockOrderIsConsistent(). This registry is
 * deliberately a hand-maintained allowlist rather than something derived by
 * scanning engine-context.js's source: the point is that removing
 * `validateAndSave` from UNSERIALIZED_METHODS requires a DELIBERATE,
 * corresponding edit here too (or the assertion fails), not that the
 * assertion tries to infer self-acquisition from source text.
 *
 * A second existing instance of the same self-acquisition SHAPE —
 * configGen.regenerateStaleConfig's injected `runProxyOperation` (`(fn) =>
 * mutexes.proxy.run(fn)`, engine-context.js) — is deliberately NOT listed
 * here. Scanned as part of this task (NCOW-49 AC#8): createEngineContext()
 * invokes regenerateStaleConfig(), and therefore this self-acquisition, once,
 * synchronously, during its own composition — and main/index.js calls
 * createEngineContext() BEFORE registerIpcHandlers() ever wires up any
 * IPC-level locking (see main/index.js's call order). So this second
 * self-acquisition is not reachable from a locked handler today and cannot
 * stack with anything. If a future change ever invokes
 * regenerateStaleConfig/runProxyOperation from inside an IPC handler (or
 * moves registerIpcHandlers() earlier), it would need its own entry here —
 * this comment exists so that scan isn't silently forgotten if that changes.
 *
 * Scope of assertUnserializedMethodsCoverSelfAcquirers()'s guarantee: it is a
 * tripwire against ONE specific regression direction — `validateAndSave`
 * dropped from UNSERIALIZED_METHODS while staying listed here, i.e. this
 * registry and reality (the method still self-acquires in engine-context.js)
 * disagreeing with UNSERIALIZED_METHODS. It does NOT, and structurally
 * cannot, catch the other direction: removing `validateAndSave` from BOTH
 * UNSERIALIZED_METHODS and this registry together while its self-acquisition
 * stays in engine-context.js — from this registry's own point of view that
 * looks like a deliberate, coordinated removal of a self-acquirer, not a
 * regression. That second direction is still caught, just by a different
 * layer: the existing behavioral test suite (ipc-mutex.test.js) drives
 * `apiKey:validateAndSave` through the real registered handler, so stacking
 * IPC-level locking back on top of the still-present inner
 * `mutexes.config.run()` call aborts the ipc-mutex.test.js run rather than
 * passing silently: the deadlocked promise chain leaves nothing on the event
 * loop, so node's test runner reports a still-pending-promise error and
 * cancels the remaining tests in that file (rather than the whole suite
 * hanging) — reproduced directly (removing `validateAndSave` from both
 * UNSERIALIZED_METHODS.apiKey and SELF_ACQUIRING_HANDLERS): 35 pass, 0 fail,
 * 29 cancelled, exit code 1, in well under a second.
 */
const SELF_ACQUIRING_HANDLERS = {
  apiKey: { validateAndSave: 'config' },
};

/**
 * NCOW-49 AC#8: throws if any domain.method named in `selfAcquiring` is
 * missing from `unserializedMethods` — i.e. if UNSERIALIZED_METHODS no
 * longer opts a self-acquiring handler out of this file's automatic
 * per-method locking, which would stack IPC-level locking on top of that
 * handler's own inner acquisition of the exact same mutex and deadlock it
 * permanently (see SELF_ACQUIRING_HANDLERS above for the full reasoning).
 */
function assertUnserializedMethodsCoverSelfAcquirers(unserializedMethods, selfAcquiring) {
  const missing = [];
  for (const [domain, methods] of Object.entries(selfAcquiring)) {
    const unserializedForDomain = unserializedMethods[domain] ?? [];
    for (const method of Object.keys(methods)) {
      if (!unserializedForDomain.includes(method)) missing.push(`${domain}.${method}`);
    }
  }
  if (missing.length > 0) {
    throw new Error(
      `${JSON.stringify(missing)} self-acquire a shared domain mutex directly (see SELF_ACQUIRING_HANDLERS) but ` +
        `${missing.length === 1 ? 'is' : 'are'} missing from UNSERIALIZED_METHODS — stacking this file's ` +
        `automatic IPC-level locking on top of that self-acquisition deadlocks permanently, since ` +
        `createDomainMutex()'s FIFO chain (mutex.js) is non-reentrant. Re-add ${missing.length === 1 ? 'it' : 'them'} ` +
        `to UNSERIALIZED_METHODS, or remove the self-acquisition and this registry entry together.`
    );
  }
}

assertUnserializedMethodsCoverSelfAcquirers(UNSERIALIZED_METHODS, SELF_ACQUIRING_HANDLERS);

/**
 * NCOW-49 AC#5: recursively (not just shallowly) freezes an object/array and
 * everything nested inside it. A shallow Object.freeze() on
 * DOMAIN_MUTEX_ALIASES would stop `DOMAIN_MUTEX_ALIASES.apiKey = 'proxy'` or
 * `delete DOMAIN_MUTEX_ALIASES.apiKey` (freeze makes top-level properties
 * non-writable/non-configurable) but would NOT stop
 * `DOMAIN_MUTEX_ALIASES.uninstall.push(...)` or
 * `DOMAIN_MUTEX_ALIASES.uninstall[0] = ...` — the nested `uninstall` ARRAY
 * is a separate object the outer freeze never touches. Reversing that
 * array's order is already harmless (resolveDomainLocks sorts by
 * LOCK_ACQUISITION_ORDER regardless, see its own comment below), but
 * adding/removing an element from it is a real membership change — exactly
 * the class of mutation this whole freeze exists to prevent. Recursing into
 * every nested value closes that gap for any current or future nested
 * shape, not just the one array that happens to exist today.
 */
function deepFreeze(value) {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const v of Object.values(value)) deepFreeze(v);
  }
  return value;
}

/**
 * NCOW-32: aliases two IPC domains onto the `proxy` mutex because their
 * handlers reach into the same shared state the `proxy` domain already
 * guards. This is the domain's *only* mutating concern for `update`:
 * `update.install()` (installUpdateAndRestart -> stopProxyForShutdown,
 * src/main/autoUpdate.js) stops the very same pm2-supervised proxy the
 * launch-time background restart and a user-clicked Start/Stop/Restart
 * already serialize against each other through mutexes.proxy.
 *
 * For `uninstall`, a single alias is not enough: `uninstall.run()`
 * (src/engine/uninstall.js) mutates THREE shared-state domains in one call —
 * it removes Claude Code's settings file (removeClaudeCodeSettings(), the
 * `claudeCode` domain), calls pm2Control.remove() (the `proxy` domain, the
 * only one NCOW-32 originally covered), and, on purge, deletes the config
 * directory (fs.rmSync(opts.configDir), the `config` domain). NCOW-45 widened
 * this entry to an array of all three so an Uninstall click is serialized
 * against every mutex it actually touches, not just proxy's — without this,
 * a purge-uninstall could still interleave with an in-flight
 * claudeCode:configure/claudeCode:remove or config:generate the same way it
 * could interleave with a background restart before NCOW-32.
 *
 * Without this alias, an Uninstall click (or an update install) could
 * interleave with an in-flight restart: pm2Control.remove()'s
 * deleteAppIfPresent()+save() racing the restart's own
 * deleteAppIfPresent()->pm2.start() can leave a running proxy behind after
 * "uninstall complete", or a config directory Uninstall is deleting out from
 * under a restart that is concurrently regenerating it, or Uninstall's
 * settings-file removal racing an in-flight claudeCode:configure/remove.
 *
 * Deliberately NOT added to MUTEX_DOMAINS in mutex.js — neither `uninstall`
 * nor `update` needs a *lock of its own*; each only needs to share locks
 * that already exist for domains with an independent mutating concern, so
 * aliasing keeps createDomainMutexes() (and its own "exactly these domains"
 * test in mutex.test.js) describing only those domains.
 *
 * Distinct from main/index.js's before-quit shutdown path, which stays
 * deliberately unserialized against these locks (a wedged pm2 must never
 * make the app unquittable, per CLAUDE.md) — that path calls
 * stopProxyForShutdown() directly, outside any IPC handler, so it is
 * unaffected by this alias table.
 *
 * NCOW-47: `apiKey` aliases onto `config` for the same reason as the two
 * above — it has a real mutating concern (validateAndSave/clear persist and
 * delete the encrypted NVIDIA key via secretStore.save()/clear(),
 * engine-context.js) that shares state with an operation the `config`
 * domain already guards: config.generate reads that same key via
 * secretStore.load() *inside* the config lock (engine-context.js's
 * config.generate). Without this alias, an in-flight `apikey:clear` IPC call
 * racing a `config:generate` could interleave a delete with a read that
 * bakes the key into litellm.env, or the reverse ordering could hand
 * generate a NO_KEY failure mid-write against a key a save() had already
 * queued behind it — either way, nothing serialized the two. (There is
 * currently no shipped UI caller for the `apiKey.clear` channel at all — see
 * src/renderer/app.js and src/renderer/views/setup-view.js, the only two
 * `window.nimProxy.apiKey.*` call sites in the app (`getMasked` and
 * `validateAndSave` — never `clear`) — so today this alias is defence-in-
 * depth against a reachable IPC race, not a click a user can actually
 * trigger. As of NCOW-50 below, `validateAndSave` no longer resolves its
 * lock through this alias at all, so the alias is load-bearing only for
 * `clear` — which, per the point just made above, is the one of apiKey's
 * two mutating methods with no UI caller of its own.) apiKey has no
 * mutating concern of its own beyond this one, so — like uninstall/update —
 * it gets no dedicated entry in MUTEX_DOMAINS (mutex.js), only this alias.
 * apiKey.getMasked is a pure read and stays exempt via UNSERIALIZED_METHODS
 * above rather than through this table.
 *
 * NCOW-50: this alias is still exactly right for `clear` — a synchronous,
 * no-network body that is correctly locked in full via this table — but
 * `validateAndSave` no longer resolves its lock through here at all: it is
 * now also listed in UNSERIALIZED_METHODS above, and instead acquires
 * `mutexes.config` itself, directly, inside engine-context.js, wrapped
 * around only the secretStore.save() call rather than the network
 * validation ahead of it. See UNSERIALIZED_METHODS's own `apiKey` entry
 * above for the full reasoning (the ~20s uninstall-freeze this was found
 * to cause) and engine-context.js's apiKey.validateAndSave for the actual
 * critical section. This alias's `apiKey: 'config'` entry below is kept
 * (not narrowed to just `clear`) precisely because `clear` still needs it —
 * removing the entry would silently unlock `clear` too.
 *
 * diagnostics.run is not the only other reader of that identical secretStore
 * key — nor is it aliased here, and neither are the other two. All three
 * read the key into a local and never persist or delete it, so nothing
 * corrupts if one of them races apiKey's validateAndSave/clear; the worst
 * case in every case below is a stale-key read, same as diagnostics.run's
 * own NOT_CONFIGURED-on-a-since-cleared-key case:
 *
 *   - diagnostics.run (engine-context.js) — deliberately NOT aliased; see
 *     the comment on diagnostics.run itself for the fuller reasoning, which
 *     as of this fix pass also names catalog.fetch and proxy.testConnection
 *     below rather than reading as a census of one.
 *   - catalog.fetch (engine-context.js) — resolves to zero locks, exactly
 *     like diagnostics.run.
 *   - proxy.testConnection (engine-context.js) — locked, but under `proxy`,
 *     not `config`; different chains means it is NOT serialized against
 *     apiKey's writes either, it just isn't unserialized for this reason —
 *     it was already locked before NCOW-47 for reasons unrelated to the key
 *     (see UNSERIALIZED_METHODS' `proxy` entry above).
 *
 * prereqs.installLitellm was also checked (NCOW-47) and needs no alias: it
 * installs via uv/pipx/pip entirely outside the config directory
 * (prereqs.js), so it has no shared state with `config` (or any other
 * domain here) to race in the first place.
 */
const DOMAIN_MUTEX_ALIASES = {
  uninstall: ['claudeCode', 'config', 'proxy'],
  update: 'proxy',
  apiKey: 'config',
};
// NCOW-49 AC#5: deep-frozen below (after LOCK_ACQUISITION_ORDER is declared)
// so neither table's membership, nested alias arrays, nor bare-string alias
// values can be mutated by a consumer after module load in a way that
// changes real lock resolution — see deepFreeze()'s own doc comment above.

/**
 * NCOW-45: the one and only order in which ANY handler in this file may
 * acquire more than one domain lock at once — alphabetical by domain name,
 * chosen with no significance beyond being fixed and easy to re-derive
 * without consulting this file (so a future change can't accidentally
 * "reorder for readability" and silently invert it). `uninstall` is
 * currently the only multi-lock acquirer (see DOMAIN_MUTEX_ALIASES above);
 * confirmed by grep across src/ and test/ during NCOW-45 that no other
 * caller anywhere in this codebase ever holds more than one of these locks
 * at once, so adopting this order cannot contradict an order something else
 * already relies on.
 *
 * Why a single fixed order is deadlock-safe: a lock-ordering deadlock needs
 * a *cycle* — caller A holding lock X while waiting on lock Y, and caller B
 * holding Y while waiting on X. That requires at least two callers that each
 * acquire more than one lock, in opposite relative orders. With only one
 * multi-lock caller in the whole codebase, no such second caller exists to
 * form the other half of a cycle, so no cycle is possible regardless of
 * which order is picked. This constant exists anyway — instead of leaving
 * `uninstall` to just acquire its three in whatever order its array
 * happens to list them — so that IF a second multi-lock handler is ever
 * added, it inherits a pre-existing convention (sort its domains by this
 * same array, e.g. via resolveDomainLocks() below) rather than inventing an
 * independent order that could conflict with this one and reintroduce the
 * exact risk this comment just ruled out.
 *
 * NCOW-49: this order being alphabetical is also what makes it independently
 * CHECKABLE, not just assertable by comment. assertLockOrderIsConsistent()
 * below now verifies this array equals `[...MUTEX_DOMAINS].sort()` exactly,
 * so a future edit that reorders it — in full, or by moving just one domain
 * (even claudeDesktop, the one domain no alias references, which the
 * membership checks alone can't catch) — fails loudly at module load instead
 * of only failing incidentally if some unrelated test's deepEqual happens to
 * also encode the order.
 */
const LOCK_ACQUISITION_ORDER = ['claudeCode', 'claudeDesktop', 'config', 'proxy'];

// NCOW-49 AC#5: all three of this file's hand-maintained lock-resolution
// registries are deep-frozen from here on — see deepFreeze()'s doc comment
// further up this file for exactly what a SHALLOW freeze would have missed
// (DOMAIN_MUTEX_ALIASES.uninstall's own nested array) and why that matters
// (membership changes to it, not just harmless reordering). SELF_ACQUIRING_
// HANDLERS is included here too (fix pass 2) for the same reason, even though
// it is declared earlier in the file: deepFreeze() only needs the object to
// already exist, not to be declared textually after this point, and freezing
// it here — alongside the other two, after deepFreeze() itself is defined —
// keeps every "freeze the lock-resolution registries" call in one place
// instead of splitting it across the file.
deepFreeze(DOMAIN_MUTEX_ALIASES);
deepFreeze(LOCK_ACQUISITION_ORDER);
deepFreeze(SELF_ACQUIRING_HANDLERS);

/**
 * NCOW-46/49: throws if `order` is not exactly a permutation of `domains`, if
 * any domain referenced anywhere in `aliases` is missing from `order`, if any
 * alias entry is an empty array, or if `order`'s actual sequence isn't
 * exactly alphabetical (see LOCK_ACQUISITION_ORDER's own doc comment for why
 * that's the checkable invariant).
 *
 * Why membership alone isn't enough (NCOW-46): resolveDomainLocks() below
 * sorts by `order.indexOf(domain)`, and Array.prototype.indexOf returns -1
 * for a domain that isn't listed. With exactly one domain missing, ordering
 * still happens to stay consistent (nothing else compares equal to it). With
 * TWO OR MORE domains missing, they all compare equal (-1 === -1), and
 * Array.prototype.sort's stability then means their relative order silently
 * collapses to whatever DOMAIN_MUTEX_ALIASES happened to list them in —
 * exactly the acquisition-order inconsistency LOCK_ACQUISITION_ORDER exists
 * to prevent, reintroduced without so much as a warning.
 *
 * Why membership alone STILL isn't enough (NCOW-49, wave-7 review): none of
 * the checks above look at `order`'s actual SEQUENCE, only its membership —
 * so moving a domain (even one no alias references at all, like
 * claudeDesktop) elsewhere in LOCK_ACQUISITION_ORDER passed every check here
 * and left the whole test suite green. The alphabetical check added below
 * closes that: LOCK_ACQUISITION_ORDER's own doc comment already commits to
 * "alphabetical by domain name... easy to re-derive without consulting this
 * file", which makes the canonical order independently computable from
 * `domains` alone (`[...domains].sort()`) rather than needing a second
 * hand-maintained copy that could itself drift.
 *
 * Also NCOW-49: an empty alias array is never meaningful — omitting the
 * alias entry entirely already means "no lock" unambiguously, so an empty
 * array can only arise from a mistake (e.g. every element removed in a
 * refactor) that would otherwise silently drop serialization for every
 * mutating method of that domain. Rejected outright, unconditionally.
 *
 * NCOW-49 AC#6's OTHER named shape — a DOMAIN_MUTEX_ALIASES key that names no
 * real IPC domain (e.g. a typo like "uninstal") — is deliberately NOT checked
 * here. That check needs CHANNELS (see assertAliasKeysAreKnownChannelDomains
 * below), a data source foreign to this function's other three inputs and to
 * every existing direct call this function already has in ipc-mutex.test.js
 * (see NCOW-46's original comment on why this is exported: "so a dedicated
 * test can also exercise it directly against deliberately-broken inputs...
 * without mutating this module's real constants"). Keeping that check in its
 * own function, called separately at module load, means this function's
 * signature and every pre-existing call to it — direct or at module load —
 * stays exactly as it already was; only the module-load site gains a second,
 * additional call to the new function.
 *
 * Called once below, at module load, against the real
 * LOCK_ACQUISITION_ORDER/MUTEX_DOMAINS/DOMAIN_MUTEX_ALIASES: every check here
 * is a handful of Set/sort operations over small arrays (negligible, and paid
 * exactly once per process, not per IPC call), and a drift between these
 * hand-maintained lists is exactly as broken on a user's machine as it is in
 * CI — a loud require()-time crash here is preferable to a build that
 * silently ships with the acquisition-order guarantee already gone. Exported
 * so a dedicated test can also exercise it directly against
 * deliberately-broken inputs (see ipc-mutex.test.js) without mutating this
 * module's real constants.
 */
function assertLockOrderIsConsistent(order, domains, aliases) {
  const orderSet = new Set(order);
  const domainSet = new Set(domains);
  const missingFromOrder = domains.filter((d) => !orderSet.has(d));
  const unknownInOrder = order.filter((d) => !domainSet.has(d));
  if (order.length !== domains.length || missingFromOrder.length > 0 || unknownInOrder.length > 0) {
    throw new Error(
      `LOCK_ACQUISITION_ORDER ${JSON.stringify(order)} must be exactly a permutation of MUTEX_DOMAINS ` +
        `${JSON.stringify(domains)} (missing: ${JSON.stringify(missingFromOrder)}, unexpected: ${JSON.stringify(unknownInOrder)})`
    );
  }

  const aliasedDomains = Object.values(aliases).flatMap((v) => (Array.isArray(v) ? v : [v]));
  const unlistedAliasDomains = [...new Set(aliasedDomains.filter((d) => !orderSet.has(d)))];
  if (unlistedAliasDomains.length > 0) {
    throw new Error(
      `DOMAIN_MUTEX_ALIASES references domain(s) ${JSON.stringify(unlistedAliasDomains)} missing from ` +
        `LOCK_ACQUISITION_ORDER ${JSON.stringify(order)}`
    );
  }

  const emptyAliasKeys = Object.entries(aliases)
    .filter(([, v]) => Array.isArray(v) && v.length === 0)
    .map(([k]) => k);
  if (emptyAliasKeys.length > 0) {
    throw new Error(
      `DOMAIN_MUTEX_ALIASES has an empty alias array for: ${JSON.stringify(emptyAliasKeys)} — name at least one ` +
        `domain to lock, or remove the entry entirely (omission already means "no lock" unambiguously)`
    );
  }

  const expectedOrder = [...domains].sort();
  if (JSON.stringify(order) !== JSON.stringify(expectedOrder)) {
    throw new Error(
      `LOCK_ACQUISITION_ORDER ${JSON.stringify(order)} must be exactly the alphabetical ordering of MUTEX_DOMAINS ` +
        `(expected ${JSON.stringify(expectedOrder)}) — its own doc comment guarantees this order is alphabetical ` +
        `and independently re-derivable; an unchecked reorder (even one preserving membership, e.g. moving a ` +
        `domain no alias references) would silently invalidate that guarantee`
    );
  }
}

assertLockOrderIsConsistent(LOCK_ACQUISITION_ORDER, MUTEX_DOMAINS, DOMAIN_MUTEX_ALIASES);

/**
 * NCOW-49 AC#6: throws if any key of `aliases` (DOMAIN_MUTEX_ALIASES) names
 * no domain in `channelDomains` (CHANNELS' top-level keys) — a typo'd key
 * (e.g. "uninstal") is invisible to assertLockOrderIsConsistent() above,
 * since resolveDomainLocks() is only ever queried with a REAL channel domain
 * name (registerIpcHandlers() iterates Object.entries(CHANNELS)), so a
 * misspelled alias key just means the intended domain's alias silently
 * doesn't exist — degrading it to zero locks with nothing above noticing.
 *
 * Kept as its own function, called separately at module load (rather than
 * folded into assertLockOrderIsConsistent as another parameter), so that
 * function's signature and every existing call to it — including the
 * deliberately-broken-input tests in ipc-mutex.test.js that predate this
 * task — stays completely unchanged; only the module-load site below gains
 * this second call.
 */
function assertAliasKeysAreKnownChannelDomains(aliases, channelDomains) {
  const channelDomainSet = new Set(channelDomains);
  const unknownAliasKeys = Object.keys(aliases).filter((k) => !channelDomainSet.has(k));
  if (unknownAliasKeys.length > 0) {
    throw new Error(
      `DOMAIN_MUTEX_ALIASES has key(s) ${JSON.stringify(unknownAliasKeys)} that name no domain in CHANNELS — a ` +
        `typo'd key here silently vanishes instead of failing (the real domain it was meant to lock then ` +
        `resolves to zero locks)`
    );
  }
}

assertAliasKeysAreKnownChannelDomains(DOMAIN_MUTEX_ALIASES, Object.keys(CHANNELS));

/**
 * NCOW-49 AC#1: true for anything that at least LOOKS like a lock produced by
 * createDomainMutex()/createDomainMutexes() (mutex.js) — duck-typed on the
 * `.run` property that constructor unconditionally attaches (see mutex.js's
 * own JSDoc: `{((fn) => Function) & {run: (fn) => Promise<any>}}`). A bare,
 * hand-rolled wrapper with no `.run` of its own at all, e.g.
 * `(fn) => realMutex(fn)` or `realMutex.bind(null)`, does NOT carry `.run` —
 * only the thing it forwards to does — so this rejects those outright.
 *
 * This check is deliberately NARROWER than its name might suggest: it does
 * NOT prove `lock` is the exact object createDomainMutex() returned, only
 * that it exposes a `.run` function. A transparent forwarding wrapper around
 * a real mutex — `new Proxy(realMutex, {})`, `Object.assign(w, realMutex)`,
 * or `w.run = realMutex.run` — carries a `.run` too (the Proxy forwards
 * property access, and the other two copy the reference), so it passes THIS
 * check while still being a distinct object from `realMutex`. Closing that
 * gap is not this function's job: see resolveDomainLocks()'s dedupe step
 * below, which keys on `lock.run` identity rather than `lock` identity for
 * exactly this reason. A wrapper that invents an entirely NEW `.run` function
 * of its own (one that internally calls through to the real chain rather
 * than forwarding/copying the existing `.run` reference) would still evade
 * both this check's spirit and that dedupe — but doing so requires writing
 * new indirection code, unlike the three forwarding shapes above, which are
 * the idiomatic way to transparently wrap an existing object in JS.
 *
 * Why this matters: the wave-7 integration review found that two DISTINCT
 * functions can silently forward onto the SAME underlying FIFO chain without
 * resolveDomainLocks()'s (then identity-based) dedupe (`seen.has(lock)`) ever
 * seeing them as equal — e.g. `{ claudeCode: (fn) => s(fn), config: s, proxy:
 * p }` resolves `uninstall` to what LOOKS like 3 distinct locks, but two of
 * them share one chain, so withLocks() reserves that chain twice and the
 * second reservation can never get its turn: a permanent deadlock,
 * reintroducing NCOW-46's hazard through indirection instead of literal
 * reuse. This check alone stops the no-`.run`-at-all shape; it takes the
 * `.run`-identity dedupe below to also stop the three forwarding shapes.
 */
function isDomainMutex(value) {
  return typeof value === 'function' && typeof value.run === 'function';
}

function assertGenuineMutex(lock, domain) {
  if (!isDomainMutex(lock)) {
    throw new Error(
      `resolveDomainLocks: mutexes.${domain} is not a lock produced by createDomainMutex()/createDomainMutexes() ` +
        `(mutex.js) — a wrapper or hand-rolled function here can silently share another domain's underlying FIFO ` +
        `chain without being caught by identity-based dedupe, reintroducing NCOW-46's deadlock through ` +
        `indirection (NCOW-49). Pass the exact function createDomainMutex()/createDomainMutexes() returned, not ` +
        `a wrapper around it.`
    );
  }
  return lock;
}

/** Resolves the ordered list of locks a domain's methods must hold before
 *  running: its own single lock if MUTEX_DOMAINS covers it, else its
 *  alias(es) from DOMAIN_MUTEX_ALIASES (normalized to an array whether the
 *  table lists one domain or several, sorted into LOCK_ACQUISITION_ORDER
 *  regardless of the order the table happens to list them in — so a future
 *  edit to that table can't silently invert the acquisition order — and
 *  deduplicated by resolved lock's `.run` identity, NOT the lock object's own
 *  identity — see the NCOW-49 fix-pass-2 paragraph below for why), else an
 *  empty array.
 *
 *  NCOW-46: the dedupe step matters even though no current
 *  DOMAIN_MUTEX_ALIASES entry resolves two of its aliased domains to the same
 *  underlying mutex function (MUTEX_DOMAINS/createDomainMutexes() hands out
 *  one distinct mutex per domain) — it IS reachable via the `opts.mutexes`
 *  injection point registerIpcHandlers() itself accepts, e.g. a hand-built
 *  mutexes object or a test fixture that reuses one mutex for two domain
 *  keys. Without deduping, withLocks() below would reserve that one
 *  underlying FIFO chain twice for the same call, and the second reservation
 *  can never get its turn — its own release depends on the shared run it is
 *  blocking, a permanent deadlock. Deduping degrades that case to holding the
 *  shared mutex once instead.
 *
 *  NCOW-49 fix pass 1: every lock this function is about to return
 *  (own-domain or aliased) is validated by assertGenuineMutex() — this
 *  rejects a bare wrapper with no `.run` of its own at all (e.g.
 *  `(fn) => s(fn)`), which was the wave-7 review's original probe.
 *
 *  NCOW-49 fix pass 2 (this fix): fix pass 1's dedupe still keyed on the lock
 *  OBJECT's own identity (`seen.has(lock)`), which a follow-up review then
 *  showed is not enough on its own — a TRANSPARENT forwarding wrapper around
 *  a genuine mutex (`new Proxy(realMutex, {})`, `Object.assign(w,
 *  realMutex)`, or `w.run = realMutex.run`) is a distinct object from
 *  `realMutex`, so it survives assertGenuineMutex() (it does carry a `.run`)
 *  AND survives object-identity dedupe (it isn't `===` to `realMutex`), while
 *  still sharing `realMutex`'s exact underlying FIFO chain — reintroducing
 *  NCOW-46's deadlock through a second layer of indirection. All three of
 *  those forwarding shapes copy or forward the ORIGINAL `.run` function by
 *  reference rather than creating a new one, so `wrapper.run ===
 *  realMutex.run` holds for all three even though `wrapper === realMutex`
 *  does not. Keying dedupe on `lock.run` instead of `lock` itself catches all
 *  three, and still catches literal same-object reuse too (if `wrapper ===
 *  realMutex`, then trivially `wrapper.run === realMutex.run`), so this is a
 *  strict widening of fix pass 1's dedupe, not a replacement of a different
 *  kind. It does NOT catch a wrapper that defines a brand-new `.run` function
 *  which merely calls through to the real chain internally (`w.run = (fn) =>
 *  realMutex.run(fn)`) — that requires deliberately writing new indirection
 *  code, unlike the three idiomatic "wrap an existing object" shapes above,
 *  and remains an accepted, deliberately-scoped-out residual limitation.
 *
 *  Also (implementation-note #4 from NCOW-49): an alias target whose mutex is
 *  entirely ABSENT from the injected `mutexes` set used to be silently
 *  dropped here (`if (!lock || seen.has(lock)) continue`) — pre-existing from
 *  NCOW-45, and worse after NCOW-47/50 since it could degrade `apiKey` all
 *  the way to zero locks, indistinguishable from a domain deliberately left
 *  unlocked. That is now a loud throw instead of a silent degrade. */
function resolveDomainLocks(mutexes, domain) {
  if (mutexes[domain]) return [assertGenuineMutex(mutexes[domain], domain)];
  const alias = DOMAIN_MUTEX_ALIASES[domain];
  if (!alias) return [];
  const aliasDomains = Array.isArray(alias) ? alias : [alias];
  const sorted = [...aliasDomains].sort(
    (a, b) => LOCK_ACQUISITION_ORDER.indexOf(a) - LOCK_ACQUISITION_ORDER.indexOf(b)
  );
  // Keyed on `lock.run` identity, not `lock` identity — see this function's
  // own doc comment (NCOW-49 fix pass 2) for why a wrapper object can be
  // `!==` its underlying mutex while still forwarding/copying the exact same
  // `.run` reference, and so must dedupe as "the same lock" anyway.
  const seenRuns = new Set();
  const locks = [];
  for (const d of sorted) {
    const lock = mutexes[d];
    if (!lock) {
      throw new Error(
        `resolveDomainLocks: "${domain}" aliases onto "${d}" (see DOMAIN_MUTEX_ALIASES) but mutexes.${d} is ` +
          `missing from the injected mutex set — this would silently drop serialization for every mutating ` +
          `method of "${domain}" instead of failing. Pass the complete set createDomainMutexes() produces, not ` +
          `a hand-built subset.`
      );
    }
    assertGenuineMutex(lock, d);
    if (seenRuns.has(lock.run)) continue;
    seenRuns.add(lock.run);
    locks.push(lock);
  }
  return locks;
}

/**
 * Composes N single-domain lock decorators into one that holds ALL of them
 * for the full duration of `fn`, reserving a queue slot on each — in
 * `locks`' order — SYNCHRONOUSLY, in the same tick, before returning.
 *
 * That synchronous, in-order reservation is what keeps a multi-lock caller's
 * position in any one shared chain consistent with a single-lock competitor
 * for that same domain: if this is invoked before a single-lock call that
 * only wants (say) the last domain in `locks`, this reserves its slot on
 * that domain's chain in the very same synchronous pass that reserves its
 * slots on every other domain — so the competitor, invoked afterwards,
 * necessarily queues behind it there too. An earlier version of this
 * function nested lock acquisition instead (only enqueuing on locks[1] once
 * locks[0]'s turn had actually arrived, and so on) — which reproduces
 * LOCK_ACQUISITION_ORDER's intended acquisition order in isolation, but lets
 * a single-lock competitor for the LAST domain in `locks` win a queue race
 * against a multi-lock caller that was invoked first, because the
 * single-lock call reaches that domain's chain in one synchronous step while
 * the multi-lock call is still working through the microtasks of its earlier
 * locks. Reserving every slot up front closes that race. (Caught by this
 * task's own regression test for AC#3 — see ipc-mutex.test.js.)
 *
 * Each reservation's callback resolves a per-lock "ready" signal and then
 * returns the SAME shared `fn(...args)` promise — so, per
 * createDomainMutex()'s own chain-of-promises design (mutex.js), every one
 * of these locks stays occupied, blocking whatever else is queued behind it,
 * until `fn` has fully settled, not merely until its own turn arrived. `fn`
 * itself only starts once every lock's ready signal has resolved, i.e. once
 * every lock's turn has arrived.
 *
 * The exactly-one-lock case is special-cased to plain `lock(fn)` rather than
 * running it through the barrier machinery below: the barrier adds a couple
 * of extra microtask hops before `fn` actually starts (resolving a "ready"
 * signal and awaiting a Promise.all of it are each their own tick), and one
 * regression-tested caller (tray-actions.test.js's mutex-identity check)
 * depends on ipc.js's own single-lock timing matching tray.js's direct
 * `mutexes.proxy.run(fn)` call tick-for-tick. Every domain but `uninstall`
 * still resolves to exactly one lock, so this keeps their behaviour, and
 * that test, byte-for-byte unchanged.
 */
function withLocks(locks, fn) {
  if (locks.length <= 1) return locks.length === 1 ? locks[0](fn) : fn;
  return (...args) => {
    const readySignals = locks.map(() => {
      let resolve;
      const promise = new Promise((res) => {
        resolve = res;
      });
      return { promise, resolve };
    });

    const sharedRun = Promise.all(readySignals.map((s) => s.promise)).then(() => fn(...args));

    for (let i = 0; i < locks.length; i++) {
      const { resolve } = readySignals[i];
      locks[i](() => {
        resolve();
        return sharedRun;
      })();
    }

    return sharedRun;
  };
}

const ALLOWED_EXTERNAL_URL_PREFIXES = [
  'https://build.nvidia.com',
  'https://claude.com/docs',
  // Broad enough to cover this project's own repo plus every dependency
  // homepage listed in the Licenses view, which are overwhelmingly GitHub.
  'https://github.com/',
  'https://gitlab.com/',
  'https://www.npmjs.com/',
];

// Handlers that don't need an engine module — always available, regardless
// of which engine domains have landed yet. Callers may still override these
// via the `handlers.app` argument if a future need arises.
const builtinAppHandlers = {
  getVersion: async () => ({ ok: true, data: app.getVersion() }),
  getPlatform: async () => ({ ok: true, data: process.platform }),
  openExternal: async ({ url } = {}) => {
    if (typeof url !== 'string' || !ALLOWED_EXTERNAL_URL_PREFIXES.some((p) => url.startsWith(p))) {
      return { ok: false, error: { code: 'URL_NOT_ALLOWED', message: 'URL is not in the allowlist' } };
    }
    await shell.openExternal(url);
    return { ok: true };
  },
  getLicenses: async () => {
    try {
      return { ok: true, data: JSON.parse(fs.readFileSync(LICENSES_PATH, 'utf8')) };
    } catch (err) {
      // A missing or corrupt file means someone shipped without running
      // `npm run licenses`. Say so plainly rather than showing an empty list
      // that reads as "this app bundles nothing".
      return {
        ok: false,
        error: { code: 'LICENSES_UNAVAILABLE', message: `Could not read licenses.json: ${err.message}` },
      };
    }
  },
};

/**
 * @param {Record<string, Record<string, Function>>} handlers
 *   Per-domain handler implementations, e.g. { proxy: { start: async () => ... } }.
 *   Any channel without a supplied handler falls back to a NOT_IMPLEMENTED stub,
 *   so this module is safe to call before every engine module has landed.
 * @param {{mutexes?: ReturnType<typeof createDomainMutexes>}} [opts]
 *   NCOW-31: the per-domain locks to serialize mutating handlers against.
 *   MUST be the same object engine-context.js used for its own background
 *   proxy work (index.js passes `context.mutexes` straight through) — a
 *   separate set here would silently mean the launch-time config regeneration
 *   and a user-initiated Start/Stop are locked against different chains, i.e.
 *   not serialized at all. Defaults to a private set only so this function
 *   stays callable in isolation. NCOW-32/NCOW-45/NCOW-47: 'uninstall',
 *   'update', and 'apiKey' have no entry of their own in this set (see
 *   mutex.js's MUTEX_DOMAINS) — they resolve onto one or more of
 *   `mutexes.{proxy,config,claudeCode}` via DOMAIN_MUTEX_ALIASES above
 *   instead. `uninstall` resolves to all three (acquired in
 *   LOCK_ACQUISITION_ORDER via withLocks(), see both above); `update` still
 *   resolves to `proxy` alone; `apiKey` resolves to `config`, but only for
 *   `clear` — `getMasked` and, as of NCOW-50, `validateAndSave` both opt out
 *   via UNSERIALIZED_METHODS above, with `validateAndSave` instead acquiring
 *   `mutexes.config` directly inside engine-context.js, scoped to just its
 *   secretStore.save() call.
 */
function registerIpcHandlers(handlers = {}, opts = {}) {
  const mergedHandlers = { ...handlers, app: { ...builtinAppHandlers, ...handlers.app } };
  const mutexes = opts.mutexes ?? createDomainMutexes();

  for (const [domain, spec] of Object.entries(CHANNELS)) {
    const domainHandlers = mergedHandlers[domain] || {};
    const locks = resolveDomainLocks(mutexes, domain);
    const unserialized = UNSERIALIZED_METHODS[domain] ?? [];
    for (const [method, channel] of Object.entries(spec.invoke || {})) {
      const impl = domainHandlers[method] || notImplemented(domain, method);
      const shouldLock = locks.length > 0 && !unserialized.includes(method);
      const wrapped = shouldLock ? withLocks(locks, impl) : impl;
      ipcMain.handle(channel, async (_event, ...args) => {
        try {
          return await wrapped(...args);
        } catch (err) {
          return { ok: false, error: { code: err.code || 'UNEXPECTED', message: err.message } };
        }
      });
    }
  }
}

module.exports = {
  registerIpcHandlers,
  // NCOW-46: exported so ipc-mutex.test.js can reference these directly
  // instead of only ever exercising them behaviorally through uninstall.
  resolveDomainLocks,
  withLocks,
  assertLockOrderIsConsistent,
  DOMAIN_MUTEX_ALIASES,
  LOCK_ACQUISITION_ORDER,
  // NCOW-49 AC#6: exported for the same reason assertLockOrderIsConsistent
  // above is — so ipc-mutex.test.js can exercise it directly against
  // deliberately-broken inputs.
  assertAliasKeysAreKnownChannelDomains,
  // NCOW-49 AC#8: exported so ipc-mutex.test.js can exercise the
  // self-acquirer guard directly against deliberately-broken inputs, the
  // same pattern assertLockOrderIsConsistent above already established.
  assertUnserializedMethodsCoverSelfAcquirers,
  SELF_ACQUIRING_HANDLERS,
};
