'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { ipcMain, app, shell } = require('electron');
const { CHANNELS } = require('./ipc-channels');
const { createDomainMutexes } = require('./mutex');

// Generated by `npm run licenses` and committed. Read through the main process
// rather than imported by the renderer: it's ~190KB of license text that has no
// business in the module graph, and the renderer's CSP sets connect-src 'none',
// so it could not fetch() the file anyway.
const LICENSES_PATH = path.join(__dirname, '..', 'assets', 'licenses.json');

function notImplemented(domain, method) {
  return async () => ({
    ok: false,
    error: { code: 'NOT_IMPLEMENTED', message: `${domain}.${method} is not implemented yet` },
  });
}

/**
 * NCOW-31: the few methods of a mutexed domain that deliberately opt OUT of
 * that domain's lock. Everything else stays locked, which is what this file did
 * for every method of all four mutexed domains before now.
 *
 * Expressed as an opt-out (not an opt-in list of locked methods) on purpose: a
 * method added to a mutexed domain later is then serialized by default, and
 * only becomes unlocked if someone deliberately names it here. The inverse
 * would silently ship new mutating handlers with no lock at all.
 *
 * Why the proxy domain needs any exemption: its lock is now also taken by
 * engine-context.js's launch-time stale-config regeneration, whose restart can
 * legitimately hold it for up to pm2Control.startOrRestart()'s 60s health-check
 * window. The renderer's boot sequence awaits proxy.getStatus() before it
 * renders anything at all (renderer/app.js) and the status pill/poller keeps
 * asking, so locking that would turn exactly the upgrade launch this
 * regeneration exists for into a blank window for up to a minute. getStatus and
 * getRecentLogs are also the only two proxy methods that are pure reads —
 * getStatus lists pm2 apps, getRecentLogs tails two log files off disk. Neither
 * touches the pm2-supervised process or any main-process state, so running one
 * mid-restart cannot corrupt anything; the worst case is a status snapshot that
 * is already stale by the time it is rendered, which is true of every poll tick
 * regardless. testConnection and start/stopLogTail stay locked: the first was
 * locked before this change and would otherwise start failing spuriously
 * against a proxy that is mid-restart, and the log-tail pair mutate
 * engine-context.js's single `logTailUnsubscribe` slot, where two interleaved
 * callers leak a subscription.
 */
const UNSERIALIZED_METHODS = {
  proxy: ['getStatus', 'getRecentLogs'],
  // NCOW-32: update:check reaches neither pm2Control nor the config
  // directory (see autoUpdate.js's performCheck — it only ever talks to
  // GitHub's Releases API on macOS, or electron-updater's own metadata
  // fetch on Windows/Linux) and is fired automatically at every app startup,
  // racing exactly the launch-time background restart that can hold the
  // proxy lock for up to 60s. update:install is the one method of this
  // domain that actually reaches into shared proxy state
  // (installUpdateAndRestart -> stopProxyForShutdown) and stays locked (see
  // DOMAIN_MUTEX_ALIASES below); queuing this pure status read behind a
  // restart would delay every update-status broadcast for no corresponding
  // safety benefit, mirroring proxy's own getStatus/getRecentLogs exemption.
  update: ['check'],
};

/**
 * NCOW-32: aliases two IPC domains onto the `proxy` mutex because their
 * handlers reach into the same shared state the `proxy` domain already
 * guards. This is the domain's *only* mutating concern for `update`:
 * `update.install()` (installUpdateAndRestart -> stopProxyForShutdown,
 * src/main/autoUpdate.js) stops the very same pm2-supervised proxy the
 * launch-time background restart and a user-clicked Start/Stop/Restart
 * already serialize against each other through mutexes.proxy.
 *
 * For `uninstall`, this alias covers that same proxy-mutex concern only —
 * `uninstall.run()` calls pm2Control.remove() directly
 * (src/engine/uninstall.js). It is NOT the domain's only mutating concern:
 * uninstall.run() also removes Claude Code's settings file
 * (removeClaudeCodeSettings()) and, on purge, deletes the config directory
 * (fs.rmSync(opts.configDir)) — both already guarded by their own mutexes
 * (mutexes.claudeCode, mutexes.config respectively), neither of which this
 * alias table touches. That gap is tracked separately as NCOW-45.
 *
 * Without this alias, an Uninstall click (or an update install) could
 * interleave with an in-flight restart: pm2Control.remove()'s
 * deleteAppIfPresent()+save() racing the restart's own
 * deleteAppIfPresent()->pm2.start() can leave a running proxy behind after
 * "uninstall complete", or a config directory Uninstall is deleting out from
 * under a restart that is concurrently regenerating it.
 *
 * Deliberately NOT added to MUTEX_DOMAINS in mutex.js — neither domain needs
 * a *lock of its own* for this proxy-shared concern, only to share proxy's,
 * so aliasing keeps createDomainMutexes() (and its own "exactly these
 * domains" test in mutex.test.js) describing only the domains with an
 * independent mutating concern.
 *
 * Distinct from main/index.js's before-quit shutdown path, which stays
 * deliberately unserialized against this same lock (a wedged pm2 must never
 * make the app unquittable, per CLAUDE.md) — that path calls
 * stopProxyForShutdown() directly, outside any IPC handler, so it is
 * unaffected by this alias table.
 */
const DOMAIN_MUTEX_ALIASES = {
  uninstall: 'proxy',
  update: 'proxy',
};

/** Resolves the lock a domain's methods should serialize against: its own,
 *  if MUTEX_DOMAINS covers it, else its alias's (see DOMAIN_MUTEX_ALIASES),
 *  else none. */
function resolveDomainLock(mutexes, domain) {
  return mutexes[domain] ?? mutexes[DOMAIN_MUTEX_ALIASES[domain]];
}

const ALLOWED_EXTERNAL_URL_PREFIXES = [
  'https://build.nvidia.com',
  'https://claude.com/docs',
  // Broad enough to cover this project's own repo plus every dependency
  // homepage listed in the Licenses view, which are overwhelmingly GitHub.
  'https://github.com/',
  'https://gitlab.com/',
  'https://www.npmjs.com/',
];

// Handlers that don't need an engine module — always available, regardless
// of which engine domains have landed yet. Callers may still override these
// via the `handlers.app` argument if a future need arises.
const builtinAppHandlers = {
  getVersion: async () => ({ ok: true, data: app.getVersion() }),
  getPlatform: async () => ({ ok: true, data: process.platform }),
  openExternal: async ({ url } = {}) => {
    if (typeof url !== 'string' || !ALLOWED_EXTERNAL_URL_PREFIXES.some((p) => url.startsWith(p))) {
      return { ok: false, error: { code: 'URL_NOT_ALLOWED', message: 'URL is not in the allowlist' } };
    }
    await shell.openExternal(url);
    return { ok: true };
  },
  getLicenses: async () => {
    try {
      return { ok: true, data: JSON.parse(fs.readFileSync(LICENSES_PATH, 'utf8')) };
    } catch (err) {
      // A missing or corrupt file means someone shipped without running
      // `npm run licenses`. Say so plainly rather than showing an empty list
      // that reads as "this app bundles nothing".
      return {
        ok: false,
        error: { code: 'LICENSES_UNAVAILABLE', message: `Could not read licenses.json: ${err.message}` },
      };
    }
  },
};

/**
 * @param {Record<string, Record<string, Function>>} handlers
 *   Per-domain handler implementations, e.g. { proxy: { start: async () => ... } }.
 *   Any channel without a supplied handler falls back to a NOT_IMPLEMENTED stub,
 *   so this module is safe to call before every engine module has landed.
 * @param {{mutexes?: ReturnType<typeof createDomainMutexes>}} [opts]
 *   NCOW-31: the per-domain locks to serialize mutating handlers against.
 *   MUST be the same object engine-context.js used for its own background
 *   proxy work (index.js passes `context.mutexes` straight through) — a
 *   separate set here would silently mean the launch-time config regeneration
 *   and a user-initiated Start/Stop are locked against different chains, i.e.
 *   not serialized at all. Defaults to a private set only so this function
 *   stays callable in isolation. NCOW-32: 'uninstall' and 'update' have no
 *   entry of their own in this set (see mutex.js's MUTEX_DOMAINS) — they
 *   resolve onto `mutexes.proxy` via DOMAIN_MUTEX_ALIASES above instead.
 */
function registerIpcHandlers(handlers = {}, opts = {}) {
  const mergedHandlers = { ...handlers, app: { ...builtinAppHandlers, ...handlers.app } };
  const mutexes = opts.mutexes ?? createDomainMutexes();

  for (const [domain, spec] of Object.entries(CHANNELS)) {
    const domainHandlers = mergedHandlers[domain] || {};
    const lock = resolveDomainLock(mutexes, domain);
    const unserialized = UNSERIALIZED_METHODS[domain] ?? [];
    for (const [method, channel] of Object.entries(spec.invoke || {})) {
      const impl = domainHandlers[method] || notImplemented(domain, method);
      const shouldLock = Boolean(lock) && !unserialized.includes(method);
      const wrapped = shouldLock ? lock(impl) : impl;
      ipcMain.handle(channel, async (_event, ...args) => {
        try {
          return await wrapped(...args);
        } catch (err) {
          return { ok: false, error: { code: err.code || 'UNEXPECTED', message: err.message } };
        }
      });
    }
  }
}

module.exports = { registerIpcHandlers };
