'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { ipcMain, app, shell } = require('electron');
const { CHANNELS } = require('./ipc-channels');

// Generated by `npm run licenses` and committed. Read through the main process
// rather than imported by the renderer: it's ~190KB of license text that has no
// business in the module graph, and the renderer's CSP sets connect-src 'none',
// so it could not fetch() the file anyway.
const LICENSES_PATH = path.join(__dirname, '..', 'assets', 'licenses.json');

function notImplemented(domain, method) {
  return async () => ({
    ok: false,
    error: { code: 'NOT_IMPLEMENTED', message: `${domain}.${method} is not implemented yet` },
  });
}

/**
 * Per-domain mutex so an overlapping mutating call (e.g. tray "Restart" and
 * window "Stop" firing together) can't race. Domains without a mutating
 * concern (app, catalog, diagnostics-read) don't need one.
 */
function createDomainMutex() {
  let chain = Promise.resolve();
  return function withLock(fn) {
    return (...args) => {
      const run = chain.then(() => fn(...args));
      // Swallow so one failed call doesn't wedge the chain for later calls.
      chain = run.catch(() => {});
      return run;
    };
  };
}

const mutexes = {
  proxy: createDomainMutex(),
  config: createDomainMutex(),
  claudeDesktop: createDomainMutex(),
  claudeCode: createDomainMutex(),
};

const ALLOWED_EXTERNAL_URL_PREFIXES = [
  'https://build.nvidia.com',
  'https://claude.com/docs',
  // Broad enough to cover this project's own repo plus every dependency
  // homepage listed in the Licenses view, which are overwhelmingly GitHub.
  'https://github.com/',
  'https://gitlab.com/',
  'https://www.npmjs.com/',
];

// Handlers that don't need an engine module — always available, regardless
// of which engine domains have landed yet. Callers may still override these
// via the `handlers.app` argument if a future need arises.
const builtinAppHandlers = {
  getVersion: async () => ({ ok: true, data: app.getVersion() }),
  getPlatform: async () => ({ ok: true, data: process.platform }),
  openExternal: async ({ url } = {}) => {
    if (typeof url !== 'string' || !ALLOWED_EXTERNAL_URL_PREFIXES.some((p) => url.startsWith(p))) {
      return { ok: false, error: { code: 'URL_NOT_ALLOWED', message: 'URL is not in the allowlist' } };
    }
    await shell.openExternal(url);
    return { ok: true };
  },
  getLicenses: async () => {
    try {
      return { ok: true, data: JSON.parse(fs.readFileSync(LICENSES_PATH, 'utf8')) };
    } catch (err) {
      // A missing or corrupt file means someone shipped without running
      // `npm run licenses`. Say so plainly rather than showing an empty list
      // that reads as "this app bundles nothing".
      return {
        ok: false,
        error: { code: 'LICENSES_UNAVAILABLE', message: `Could not read licenses.json: ${err.message}` },
      };
    }
  },
};

/**
 * @param {Record<string, Record<string, Function>>} handlers
 *   Per-domain handler implementations, e.g. { proxy: { start: async () => ... } }.
 *   Any channel without a supplied handler falls back to a NOT_IMPLEMENTED stub,
 *   so this module is safe to call before every engine module has landed.
 */
function registerIpcHandlers(handlers = {}) {
  const mergedHandlers = { ...handlers, app: { ...builtinAppHandlers, ...handlers.app } };

  for (const [domain, spec] of Object.entries(CHANNELS)) {
    const domainHandlers = mergedHandlers[domain] || {};
    const lock = mutexes[domain];
    for (const [method, channel] of Object.entries(spec.invoke || {})) {
      const impl = domainHandlers[method] || notImplemented(domain, method);
      const wrapped = lock ? lock(impl) : impl;
      ipcMain.handle(channel, async (_event, ...args) => {
        try {
          return await wrapped(...args);
        } catch (err) {
          return { ok: false, error: { code: err.code || 'UNEXPECTED', message: err.message } };
        }
      });
    }
  }
}

module.exports = { registerIpcHandlers };
